#!/usr/bin/env python3
"""Generate data/ninos-cuentos.json with bilingual children's saint stories."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from ninos_bedtime import expand_bedtime

OUT = ROOT / "data" / "ninos-cuentos.json"

def S(id_, saint, icon, accent, title_es, title_en, hook_es, hook_en,
       story_es, story_en, moral_es, moral_en, act_es, act_en):
    return {
        "id": id_,
        "saintId": saint,
        "icon": f"/assets/images/{icon}",
        "accent": accent,
        "title": {"es": title_es, "en": title_en},
        "hook": {"es": hook_es, "en": hook_en},
        "story": {"es": story_es, "en": story_en},
        "moral": {"es": moral_es, "en": moral_en},
        "activity": {"es": act_es, "en": act_en},
    }

CUENTOS = [
S("juanbosco","sanjuanbosco","sanjuanbosco.svg","#5a8fd4",
  "Don Bosco y los muchachos","Don Bosco and the boys",
  "Un cura que jugaba con los niños de la calle","A priest who played with street children",
  "Hace mucho tiempo, en Italia, vivía un sacerdote llamado Juan Bosco. Veía a niños sin escuela ni hogar. En lugar de gritarles, los invitaba a jugar, cantar y aprender sobre Jesús.\n\nDon Bosco les decía: «Dios te quiere feliz.» Les enseñaba con paciencia. Muchos de esos niños se convirtieron en personas buenas.\n\nHoy la Iglesia lo llama padre de la juventud. Puedes pedirle que te ayude a encontrar amigos buenos.",
  "Long ago in Italy lived a priest named John Bosco. He saw children with no school or home. Instead of shouting, he invited them to play, sing, and learn about Jesus.\n\nDon Bosco said: \"God wants you to be happy.\" He taught with patience. Many of those children became good people.\n\nToday the Church calls him father of youth. You can ask him to help you find good friends.",
  "Jesús ama a todos los niños — especialmente a los que nadie mira.",
  "Jesus loves all children — especially those nobody notices.",
  "Invita hoy a un niño que esté solo a jugar contigo.",
  "Today invite a child who is alone to play with you."),

S("teresita","santateresita","santateresita.svg","#d45a8a",
  "Teresita y el caminito pequeño","Little Thérèse and the little way",
  "Cosas chiquitas hechas con mucho amor","Tiny things done with great love",
  "Teresita era sensible pero amaba mucho a Jesús. Descubrió que no hace falta hacer cosas enormes para ser santa.\n\nPodías ser santa sonriendo cuando no tenías ganas o ayudando sin quejarte. Lo llamó «el caminito pequeño».\n\nMurió joven, pero llenó el mundo de luz.",
  "Thérèse was sensitive but loved Jesus deeply. She discovered you do not need huge deeds to be a saint.\n\nYou could be holy by smiling when you did not feel like it or helping without complaining. She called it \"the little way.\"\n\nShe died young but filled the world with light.",
  "Lo pequeño hecho con amor es grandísimo ante Dios.",
  "Small things done with love are enormous before God.",
  "Haz una cosa pequeña con amor hoy.",
  "Do one small thing with love today."),

S("nicolas","sannicolas","sannicolas.svg","#3a5aaa",
  "San Nicolás y los zapatos secretos","Saint Nicholas and the secret shoes",
  "Regalos escondidos sin buscar aplauso","Hidden gifts without seeking applause",
  "San Nicolás amaba a los niños pobres. Una noche dejó monedas en los zapatos de tres hermanas para que su familia comiera.\n\nNo quiso que lo aplaudieran. Hizo el bien en secreto.\n\nPor eso muchos lo recuerdan en Navidad: la generosidad alegra el corazón.",
  "Saint Nicholas loved poor children. One night he left coins in three sisters' shoes so their family could eat.\n\nHe did not want applause. He did good in secret.\n\nThat is why many remember him at Christmas: generosity makes the heart glad.",
  "Dar en secreto también es amar como Jesús.",
  "Giving in secret is also loving like Jesus.",
  "Haz un regalo pequeño sin decir que fuiste tú.",
  "Give a small gift without saying it was you."),

S("francisco","sanfrancisco","sanfrancisco.svg","#8a6a3a",
  "Francisco y los animalitos","Francis and the little animals",
  "El santo que hablaba con los pájaros","The saint who talked to birds",
  "Francisco amaba a Jesús y a todo lo que Dios creó. Predicó a unos pájaros y ellos se quedaron escuchando.\n\nLlamaba hermano Sol y hermana Luna. Veía en cada cosa un regalo del Padre.\n\nNos enseña a cuidar la creación con ternura.",
  "Francis loved Jesus and all God created. He preached to birds and they stayed to listen.\n\nHe called the sun brother and moon sister. He saw every thing as the Father's gift.\n\nHe teaches us to care for creation with tenderness.",
  "El mundo es regalo de Dios — cuídalo.",
  "The world is God's gift — care for it.",
  "Cuida hoy una planta o un animal.",
  "Today care for a plant or an animal."),

S("juandiego","sanjuandiego","sanjuandiego.svg","#c97840",
  "Juan Diego y las rosas de invierno","Juan Diego and the winter roses",
  "Flores imposibles y una Madre que escucha","Impossible flowers and a Mother who listens",
  "Juan Diego era humilde. La Virgen se le apareció y le pidió hablar con el obispo. Él dudaba porque era pobre.\n\nMaría le dijo: «¿No estoy yo aquí, que soy tu Madre?» Le mandó recoger rosas en invierno.\n\nEn su tilma quedó la imagen de la Virgen morena. Dios usa a los pequeños para milagros grandes.",
  "Juan Diego was humble. Our Lady appeared and asked him to speak with the bishop. He doubted because he was poor.\n\nMary said: \"Am I not here, who am your Mother?\" She told him to gather roses in winter.\n\nOn his tilma remained the image of Our Lady. God uses the small for great miracles.",
  "María escucha a los humildes.",
  "Mary listens to the humble.",
  "Cuéntale a la Virgen algo que te preocupe.",
  "Tell the Virgin something that worries you."),

S("lucia","santalucia","santalucia.svg","#e8c040",
  "Santa Lucía y la luz","Saint Lucy and the light",
  "Luz cuando todo está oscuro","Light when all is dark",
  "Lucía ayudaba a los pobres llevándoles comida de noche. Ponía velas en la cabeza para ver.\n\nNo renunció a su fe aunque fuera difícil. Su nombre significa «luz».\n\nCuando tengas miedo, pídele a Jesús una lucecita en el corazón.",
  "Lucy helped the poor by bringing food at night. She wore candles on her head to see.\n\nShe did not give up her faith though it was hard. Her name means \"light.\"\n\nWhen you are afraid, ask Jesus for a little light in your heart.",
  "Jesús es luz — aunque afuera esté oscuro.",
  "Jesus is light — even when it is dark outside.",
  "Enciende una velita y ora un Ave María.",
  "Light a candle and pray a Hail Mary."),

S("fatima","fatima","fatima.svg","#4a7ab8",
  "Los tres pastorcitos","The three little shepherds",
  "Niños que vieron a la Virgen","Children who saw Our Lady",
  "Lucía, Francisco y Jacinta cuidaban ovejas en Portugal. La Virgen se les apareció y pidió rezar el rosario por la paz.\n\nObedecieron aunque algunos adultos no creyeron. Un día miles vieron el sol danzar en el cielo.\n\nDios escucha a los niños que confían y rezan.",
  "Lucia, Francisco, and Jacinta tended sheep in Portugal. Our Lady appeared and asked them to pray the Rosary for peace.\n\nThey obeyed though some adults did not believe. One day thousands saw the sun dance in the sky.\n\nGod listens to children who trust and pray.",
  "Rezar el rosario es un gran regalo.",
  "Praying the Rosary is a great gift.",
  "Reza un misterio del rosario con tu familia.",
  "Pray one mystery of the Rosary with your family."),

S("divinonino","divinonino","divinonino.svg","#d4a85a",
  "El Niño Jesús que sonríe","The smiling Child Jesus",
  "Jesús también fue niño","Jesus was also a child",
  "Jesús nació en Belén como un bebé. Creció jugando y aprendiendo. Por eso te entiende cuando estás triste.\n\nEl Divino Niño abre los brazos y dice: confía en mí.\n\nPuedes hablarle como a tu mejor amigo.",
  "Jesus was born in Bethlehem as a baby. He grew up playing and learning. That is why He understands when you are sad.\n\nThe Divine Child opens His arms and says: trust Me.\n\nYou can talk to Him like your best friend.",
  "Jesús fue niño. Puedes contarle todo.",
  "Jesus was a child. You can tell Him everything.",
  "Cuéntale a Jesús tres cosas de tu día.",
  "Tell Jesus three things about your day."),

S("sanjose","sanjose","sanjose.svg","#7a5e18",
  "San José, papá de Jesús","Saint Joseph, father of Jesus",
  "El carpintero que cuidó al Niño Dios","The carpenter who cared for God’s Child",
  "San José era justo y trabajador. Cuando supo que María esperaba al Hijo de Dios, confió en el ángel y la protegió.\n\nEnseñó a Jesús a trabajar, rezar y obedecer. Nunca habla en el Evangelio, pero su amor habla fuerte.\n\nEs patrón de las familias y de los que trabajan.",
  "Saint Joseph was just and hardworking. When he learned Mary carried God's Son, he trusted the angel and protected her.\n\nHe taught Jesus to work, pray, and obey. He never speaks in the Gospel, but his love speaks loudly.\n\nHe is patron of families and workers.",
  "Trabajar bien y amar en familia también es santidad.",
  "Working well and loving family is also holiness.",
  "Ayuda en casa como San José ayudaba a la Sagrada Familia.",
  "Help at home as Joseph helped the Holy Family."),

S("guadalupe","guadalupe","guadalupe.svg","#7a6010",
  "La Virgen de Guadalupe","Our Lady of Guadalupe",
  "Una Madre que dejó su imagen en un ayate","A Mother who left her image on a cloak",
  "En México, la Virgen se apareció a Juan Diego con rostro moreno, como su pueblo. Quería que supieran que los amaba a todos.\n\nDejó su imagen milagrosa en la tilma. Millones la visitan porque se sienten acogidos.\n\nElla repite: «¿No estoy yo aquí, que soy tu Madre?»",
  "In Mexico, Our Lady appeared to Juan Diego with a mestizo face like his people. She wanted them to know she loved them all.\n\nShe left her miraculous image on the tilma. Millions visit because they feel welcomed.\n\nShe repeats: \"Am I not here, who am your Mother?\"",
  "María ama a todos los pueblos.",
  "Mary loves all peoples.",
  "Pon flores o una vela en casa en su honor.",
  "Place flowers or a candle at home in her honor."),

S("sanantonio","sanantonio","sanantonio.svg","#6a3018",
  "San Antonio encuentra lo perdido","Saint Anthony finds what is lost",
  "El santo de las cosas extraviadas","The saint of lost things",
  "San Antonio predicaba con tanta claridad que hasta los peces salían del agua a escuchar. Era muy generoso con los pobres.\n\nPor eso la gente le pide ayuda cuando pierde algo: llaves, tarea, paz interior.\n\nAntonio enseña que Dios cuida hasta los detalles pequeños.",
  "Saint Anthony preached so clearly that even fish came to listen. He was very generous to the poor.\n\nPeople ask his help when they lose something: keys, homework, inner peace.\n\nAnthony teaches that God cares for even small details.",
  "Dios no pierde de vista lo que tú valoras.",
  "God does not lose sight of what you value.",
  "Reza a San Antonio si perdiste algo hoy.",
  "Pray to Saint Anthony if you lost something today."),

S("sanmiguel","sanmiguel","sanmiguel.svg","#253070",
  "San Miguel vence al mal","Saint Michael defeats evil",
  "El arcángel valiente","The brave archangel",
  "San Miguel es un arcángel, un espíritu de luz al servicio de Dios. En el cielo luchó contra el mal y gritó: «¿Quién como Dios?»\n\nProtege a quienes piden su ayuda. No tenemos miedo solos: los ángeles pelean con nosotros.\n\nCuando algo te asuste, llama a San Miguel.",
  "Saint Michael is an archangel, a spirit of light serving God. In heaven he fought evil and cried: \"Who is like God?\"\n\nHe protects those who ask. We are not alone in fear: angels fight with us.\n\nWhen something scares you, call on Saint Michael.",
  "Dios es más fuerte que cualquier miedo.",
  "God is stronger than any fear.",
  "Di esta frase: «San Miguel, protégeme hoy.»",
  "Say: \"Saint Michael, protect me today.\""),

S("sangabriel","sangabriel","sangabriel.svg","#1a3a6b",
  "Gabriel trae buenas noticias","Gabriel brings good news",
  "El ángel del Anuncio","The angel of the Annunciation",
  "Gabriel fue el ángel que le dijo a María: «Vas a ser la Madre del Salvador.» También anunció el nacimiento de Juan Bautista.\n\nLos ángeles son mensajeros de Dios. Traen palabras de paz, no de miedo.\n\nCuando escuches «no tengas miedo» en la Biblia, recuerda a Gabriel.",
  "Gabriel was the angel who told Mary: \"You will be the Mother of the Savior.\" He also announced John the Baptist's birth.\n\nAngels are God's messengers. They bring words of peace, not fear.\n\nWhen you hear \"do not be afraid\" in the Bible, remember Gabriel.",
  "Dios siempre encuentra la manera de hablarnos.",
  "God always finds a way to speak to us.",
  "Escribe o dibuja un mensaje bueno para alguien.",
  "Write or draw a kind message for someone."),

S("sanrafael","sanrafael","sanrafael.svg","#1a5c3a",
  "San Rafael acompaña al viajero","Saint Raphael accompanies the traveler",
  "El ángel que camina contigo","The angel who walks with you",
  "En la Biblia, Rafael acompañó a un joven en un viaje peligroso y lo protegió. Su nombre significa «Dios sana».\n\nIntercede por los enfermos y los que viajan. A veces Dios envía ayuda por personas — o ángeles — que no esperábamos.\n\nPídele compañía en cada camino.",
  "In the Bible, Raphael accompanied a youth on a dangerous journey and protected him. His name means \"God heals.\"\n\nHe intercedes for the sick and travelers. Sometimes God sends help through people — or angels — we did not expect.\n\nAsk for his company on every path.",
  "No caminas solo: Dios envía compañía.",
  "You do not walk alone: God sends company.",
  "Ora por alguien que esté enfermo o de viaje.",
  "Pray for someone who is sick or traveling."),

S("carlo","sancarlosacutis","sancarlosacutis.svg","#4a6a9a",
  "Carlo y la Eucaristía","Carlo and the Eucharist",
  "Un adolescente amigo de Jesús en la Hostia","A teen friend of Jesus in the Host",
  "Carlo Acutis amaba la Eucaristía. Decía que en un solo tabernáculo hay más tesoros que en el mundo entero.\n\nUsaba internet para hablar bien de Dios. Ayudaba a compañeros y a pobres.\n\nMurió muy joven, pero mostró que la santidad es posible hoy, con videojuegos y deberes.",
  "Carlo Acutis loved the Eucharist. He said one tabernacle holds more treasure than the whole world.\n\nHe used the internet to speak well of God. He helped classmates and the poor.\n\nHe died very young but showed holiness is possible today, with games and homework.",
  "Jesús en la Eucaristía es el tesoro más grande.",
  "Jesus in the Eucharist is the greatest treasure.",
  "Visita un tabernáulo y di: «Hola, Jesús.»",
  "Visit a tabernacle and say: \"Hello, Jesus.\""),

S("luisgonzaga","sanluisgonzaga","sanluisgonzaga.svg","#5a7a4a",
  "Luis Gonzaga, joven puro","Aloysius Gonzaga, pure youth",
  "Renunció a ser príncipe por amor a Dios","He gave up being a prince for love of God",
  "Luis era noble y podía tener todo. Eligió servir a Dios y cuidar enfermos durante una epidemia.\n\nMurió joven cuidando a otros. No buscó fama: buscó amar.\n\nPatrono de la juventud, enseña que la pureza es libertad.",
  "Aloysius was noble and could have everything. He chose to serve God and care for the sick in an epidemic.\n\nHe died young caring for others. He did not seek fame: he sought to love.\n\nPatron of youth, he teaches that purity is freedom.",
  "Amar a Dios vale más que cualquier corona.",
  "Loving God is worth more than any crown.",
  "Haz un acto de caridad por alguien enfermo.",
  "Do a charitable act for someone who is sick."),

S("mariagoretti","santamariagoretti","santamariagoretti.svg","#8a3050",
  "María Goretti perdona","Maria Goretti forgives",
  "Valentía y perdón a los once años","Courage and forgiveness at eleven",
  "María Goretti defendió su pureza y murió muy joven. Antes de morir perdonó a quien la hirió.\n\nEse hombre después se arrepintió y cambió de vida. El perdón puede transformar corazones.\n\nMaría nos enseña valentía y misericordia.",
  "Maria Goretti defended her purity and died very young. Before dying she forgave the one who hurt her.\n\nThat man later repented and changed his life. Forgiveness can transform hearts.\n\nMaria teaches us courage and mercy.",
  "Perdonar es difícil, pero libera el corazón.",
  "Forgiving is hard, but it frees the heart.",
  "Ora por alguien que te hizo daño.",
  "Pray for someone who hurt you."),

S("santaines","santaines","santaines.svg","#8a1a5a",
  "Santa Inés y la valentía","Saint Agnes and courage",
  "Joven fiel aunque costara caro","A young girl faithful though it cost dearly",
  "Inés era una joven romana que amaba a Jesús más que a la fama o comodidad. Prefirió ser fiel aunque fuera difícil.\n\nSu valentía inspiró a muchos. A veces ser fiel a Dios pide coraje.\n\nPídele fuerza para hacer lo correcto.",
  "Agnes was a Roman girl who loved Jesus more than fame or comfort. She chose faithfulness though it was hard.\n\nHer courage inspired many. Sometimes being faithful to God takes bravery.\n\nAsk her for strength to do what is right.",
  "Elegir a Dios es la mayor valentía.",
  "Choosing God is the greatest courage.",
  "Di «no» a algo que sabes que no está bien.",
  "Say \"no\" to something you know is not right."),

S("carloslwanga","sancarloslwanga","sancarloslwanga.svg","#4a1a08",
  "Carlos Lwanga y sus amigos","Charles Lwanga and his friends",
  "Jóvenes valientes en África","Brave young men in Africa",
  "Carlos y sus compañeros eran sirvientes de un rey cruel en África. No quisieron renunciar a su fe.\n\nPrefirieron morir antes que traicionar a Jesús. Su valentía iluminó a todo un continente.\n\nNos recuerdan que la fe puede ser heroica.",
  "Charles and his companions served a cruel king in Africa. They would not renounce their faith.\n\nThey preferred to die rather than betray Jesus. Their courage lit up a continent.\n\nThey remind us faith can be heroic.",
  "Ser fiel a Jesús vale la pena.",
  "Being faithful to Jesus is worth it.",
  "Defiende a alguien que está siendo molestado.",
  "Stand up for someone being bullied."),

S("padrepio","padrepio","padrepio.svg","#5a3828",
  "Padre Pío y la confesión","Padre Pio and Confession",
  "El fraile que ayudaba a volver a Dios","The friar who helped people return to God",
  "Padre Pío llevó en su cuerpo señales de la Pasión de Jesús. Pasaba horas en confesionario perdonando pecados.\n\nDecía que el confessionario es el lugar más hermoso de la tierra. Allí Jesús abraza al que vuelve.\n\nNo tengas miedo de confesarte.",
  "Padre Pio bore the wounds of Jesus' Passion. He spent hours in the confessional forgiving sins.\n\nHe said the confessional is the most beautiful place on earth. There Jesus embraces those who return.\n\nDo not be afraid to go to Confession.",
  "Dios siempre recibe al que vuelve.",
  "God always welcomes those who return.",
  "Pide a tus papás ir a confesión pronto.",
  "Ask your parents to go to Confession soon."),

S("teresacalcuta","teresacalcuta","teresacalcuta.svg","#1a3a7a",
  "Madre Teresa y los pobres","Mother Teresa and the poor",
  "Pequeñas cosas con gran amor","Small things with great love",
  "Madre Teresa cuidaba a los más pobres en las calles de Calcuta. Les daba comida, abrazos y dignidad.\n\nDecía: «Podemos hacer cosas pequeñas con gran amor.» No necesitaba ser famosa.\n\nNos invita a ver a Jesús en quien sufre.",
  "Mother Teresa cared for the poorest in Calcutta's streets. She gave food, hugs, and dignity.\n\nShe said: \"We can do small things with great love.\" She did not need to be famous.\n\nShe invites us to see Jesus in those who suffer.",
  "Servir al pobre es servir a Jesús.",
  "Serving the poor is serving Jesus.",
  "Comparte comida o ropa con quien lo necesite.",
  "Share food or clothes with someone in need."),

S("sanvicente","sanvicente","sanvicente.svg","#1a3a6a",
  "San Vicente de Paúl","Saint Vincent de Paul",
  "Organizó ayuda para los necesitados","He organized help for those in need",
  "San Vicente vio gente durmiendo en la calle y no se quedó de brazos cruzados. Creó grupos para visitar enfermos y dar comida.\n\nEnseñó que la caridad no es solo sentir: es hacer.\n\nTú también puedes organizar ayuda en tu familia o parroquia.",
  "Saint Vincent saw people sleeping in the street and did not stand idle. He created groups to visit the sick and give food.\n\nHe taught charity is not only feeling: it is doing.\n\nYou too can organize help in your family or parish.",
  "Ver y actuar es amor verdadero.",
  "Seeing and acting is true love.",
  "Guarda una lata para donar a los pobres.",
  "Save a jar to donate to the poor."),

S("sanjudas","sanjudas","sanjudas.svg","#1a6a3a",
  "San Judas Tadeo","Saint Jude Thaddeus",
  "El santo de lo imposible","The saint of the impossible",
  "Cuando todo parece perdido, muchos recurren a San Judas. Él fue apóstol de Jesús y anunció el Evangelio con valentía.\n\nSu intercesión recuerda que Dios puede más que nuestros problemas.\n\nNo es magia: es confianza en Dios.",
  "When all seems lost, many turn to Saint Jude. He was an apostle of Jesus and preached the Gospel bravely.\n\nHis intercession reminds us God is greater than our problems.\n\nIt is not magic: it is trust in God.",
  "Nunca es tarde para pedir ayuda a Dios.",
  "It is never too late to ask God for help.",
  "Reza a San Judas por una causa difícil.",
  "Pray to Saint Jude for a hard situation."),

S("sancharbel","sancharbel","sancharbel.svg","#6a5030",
  "San Charbel el ermitaño","Saint Charbel the hermit",
  "Silencio, oración y milagros","Silence, prayer, and miracles",
  "Charbel vivió muchos años en una montaña de Líbano, rezando en silencio. Pocos lo conocían, pero muchos recibieron milagros después de su muerte.\n\nNos enseña el poder del silencio ante Dios.\n\nA veces hay que apagar el ruido para escuchar a Jesús.",
  "Charbel lived many years on a Lebanese mountain, praying in silence. Few knew him, but many received miracles after his death.\n\nHe teaches the power of silence before God.\n\nSometimes we must turn off noise to hear Jesus.",
  "El silencio también es oración.",
  "Silence is also prayer.",
  "Apaga la pantalla diez minutos y quédate en silencio.",
  "Turn off the screen ten minutes and stay in silence."),

S("sanjorge","sanjorge","sanjorge.svg","#8a2020",
  "San Jorge y el dragón","Saint George and the dragon",
  "Valentía contra el mal","Courage against evil",
  "La leyenda cuenta que San Jorge defendió a un pueblo de un dragón. Es símbolo de luchar contra lo malo.\n\nNo siempre hay dragones reales, pero sí tentaciones y miedos.\n\nPide a San Jorge valor para elegir el bien.",
  "Legend says Saint George defended a town from a dragon. He symbolizes fighting evil.\n\nThere are not always real dragons, but there are temptations and fears.\n\nAsk Saint George for courage to choose good.",
  "Con Dios, el bien siempre puede vencer.",
  "With God, good can always win.",
  "Di «no» valiente a una tentación hoy.",
  "Bravely say \"no\" to a temptation today."),

S("sanbenito","sanbenito","sanbenito.svg","#3a3a5a",
  "San Benito y la regla","Saint Benedict and the rule",
  "Orden, oración y trabajo","Prayer, work, and order",
  "San Benito fundó monasterios donde los monjes rezaban, trabajaban y estudiaban. Su lema era: «Ora et labora» — reza y trabaja.\n\nNos enseña que la vida tiene ritmo: tiempo para Dios, estudio y descanso.\n\nTú también puedes ordenar tu día.",
  "Saint Benedict founded monasteries where monks prayed, worked, and studied. His motto was: \"Ora et labora\" — pray and work.\n\nHe teaches life has rhythm: time for God, study, and rest.\n\nYou too can order your day.",
  "Un día ordenado ayuda a amar a Dios.",
  "An ordered day helps us love God.",
  "Haz una lista simple: oración, tarea, juego, descanso.",
  "Make a simple list: prayer, homework, play, rest."),

S("sanblas","sanblas","sanblas.svg","#5a6a8a",
  "San Blas y las gargantas","Saint Blas and sore throats",
  "El santo que cuida cuando estamos enfermos","The saint who cares when we are sick",
  "San Blas era médico y obispo. Sanó a un niño que se ahogaba con una espina. Por eso se le pide por la garganta y la salud.\n\nCuando estamos enfermos, los santos interceden y los médicos ayudan.\n\nDios cuida nuestro cuerpo también.",
  "Saint Blas was a doctor and bishop. He healed a child choking on a bone. That is why people ask him for throat and health needs.\n\nWhen we are sick, saints intercede and doctors help.\n\nGod cares for our body too.",
  "Pedir sanación es un acto de fe.",
  "Asking for healing is an act of faith.",
  "Ora por alguien que esté enfermo hoy.",
  "Pray for someone who is sick today."),

S("sancamilo","sancamilo","sancamilo.svg","#6a3040",
  "San Camilo y los enfermos","Saint Camillus and the sick",
  "El enfermero santo","The saint nurse",
  "Camilo era soldado y jugador, pero cambió de vida. Fundó hospitales y cuidaba enfermos con ternura.\n\nDecía que servir al enfermo es servir a Jesús mismo.\n\nLos médicos y enfermeras son héroes silenciosos.",
  "Camillus was a soldier and gambler but changed his life. He founded hospitals and cared for the sick tenderly.\n\nHe said serving the sick is serving Jesus Himself.\n\nDoctors and nurses are silent heroes.",
  "Cuidar al enfermo es muy santo.",
  "Caring for the sick is very holy.",
  "Haz una tarjeta para alguien que esté en cama.",
  "Make a card for someone who is in bed."),

S("sanperegrino","sanperegrino","sanperegrino.svg","#4a5a3a",
  "San Peregrino y el cáncer","Saint Peregrine and cancer",
  "Milagro de sanación y paciencia","Miracle of healing and patience",
  "Peregrino tuvo una enfermedad grave en la pierna. Oró mucho y fue sanado milagrosamente. Desde entonces intercede por enfermos de cáncer.\n\nNos enseña a no perder la esperanza cuando el cuerpo sufre.\n\nDios escucha las oraciones persistentes.",
  "Peregrine had a serious leg illness. He prayed much and was miraculously healed. Since then he intercedes for those with cancer.\n\nHe teaches us not to lose hope when the body suffers.\n\nGod hears persistent prayer.",
  "La esperanza no se rinde.",
  "Hope does not give up.",
  "Ora por alguien con enfermedad grave.",
  "Pray for someone with a serious illness."),

S("sanexpedito","sanexpedito","sanexpedito.svg","#8a2010",
  "San Expedito y la prisa","Saint Expeditus and hurry",
  "Cuando necesitas ayuda ya","When you need help right now",
  "La gente recurre a San Expedito en urgencias: exámenes, problemas, miedos. Su nombre suena a «rápido».\n\nLo importante no es la prisa mágica, sino confiar en Dios cuando estamos angustiados.\n\nJesús también estuvo angustiado y oró.",
  "People turn to Saint Expeditus in emergencies: tests, problems, fears. His name sounds like \"fast.\"\n\nWhat matters is not magic speed, but trusting God when we are anxious.\n\nJesus was also anxious and prayed.",
  "En la urgencia, primero ora.",
  "In urgency, pray first.",
  "Antes de un examen, di una oración corta.",
  "Before a test, say a short prayer."),

S("sancristobal","sancristobal","sancristobal.svg","#1a5a3a",
  "San Cristóbal lleva a Jesús","Saint Christopher carries Jesus",
  "El gigante bueno","The good giant",
  "Cristóbal era muy fuerte. Un día cargó a un niño en un río. El niño se volvió pesadísimo: era Jesús con el peso del mundo.\n\nPor eso es patrón de viajeros y conductores.\n\nPídele protección en cada viaje.",
  "Christopher was very strong. One day he carried a child across a river. The child became heavy: it was Jesus carrying the world's weight.\n\nThat is why he is patron of travelers and drivers.\n\nAsk his protection on every trip.",
  "Jesús viaja contigo.",
  "Jesus travels with you.",
  "Reza antes de subir al carro o autobús.",
  "Pray before getting in the car or bus."),

S("santaana","santaana","santaana.svg","#6a4a2a",
  "Santa Ana, abuela de Jesús","Saint Anne, grandmother of Jesus",
  "La mamá de María","Mary’s mother",
  "Santa Ana fue la madre de la Virgen María y abuela de Jesús. Enseñó a María a amar a Dios desde pequeña.\n\nNos recuerda que abuelos y abuelas son un tesoro.\n\nAgradece hoy a quienes te cuidan.",
  "Saint Anne was Mary's mother and Jesus' grandmother. She taught Mary to love God from childhood.\n\nShe reminds us grandparents are a treasure.\n\nThank those who care for you today.",
  "La familia es escuela de fe.",
  "Family is a school of faith.",
  "Llama o abraza a un abuelo o abuela.",
  "Call or hug a grandparent."),

S("santamonica","santamonica","santamonica.svg","#5a4a6a",
  "Santa Mónica que no dejó de orar","Saint Monica who never stopped praying",
  "Una mamá que oró años por su hijo","A mother who prayed years for her son",
  "Mónica oró muchísimo por su hijo Agustín cuando vivía lejos de Dios. Al final él se convirtió en un gran santo.\n\nNos enseña que la oración persistente de los papás importa.\n\nNunca dejes de orar por quien amas.",
  "Monica prayed greatly for her son Augustine when he lived far from God. In the end he became a great saint.\n\nShe teaches that parents' persistent prayer matters.\n\nNever stop praying for those you love.",
  "Orar por otros es un regalo enorme.",
  "Praying for others is a huge gift.",
  "Ora hoy por tus papás o hermanos.",
  "Pray today for your parents or siblings."),

S("sanpedro","sanpedro","sanpedro.svg","#4a4a7a",
  "San Pedro y las llaves","Saint Peter and the keys",
  "El pescador que Jesús llamó","The fisherman Jesus called",
  "Pedro era pescador. Jesús le dijo: «Sígueme.» A veces falló, como cuando negó a Jesús, pero lloró y volvió.\n\nJesús le dio las llaves de la Iglesia. Pedro nos enseña que se puede fallar y volver.",
  "Peter was a fisherman. Jesus said: \"Follow Me.\" He failed sometimes, like when he denied Jesus, but he wept and returned.\n\nJesus gave him the keys of the Church. Peter teaches we can fail and come back.",
  "Volver a Jesús siempre es posible.",
  "Returning to Jesus is always possible.",
  "Si fallaste, di «Señor, perdóname» y vuelve.",
  "If you failed, say \"Lord, forgive me\" and return."),

S("sanjuanbautista","sanjuanbautista","sanjuanbautista.svg","#6a5a30",
  "Juan el Bautista","John the Baptist",
  "El que preparó el camino","The one who prepared the way",
  "Juan predicaba en el desierto: «Preparen el camino del Señor.» Bautizó a Jesús en el río Jordán.\n\nFue valiente y le dijo la verdad incluso a reyes.\n\nNos invita a preparar el corazón para recibir a Jesús.",
  "John preached in the desert: \"Prepare the way of the Lord.\" He baptized Jesus in the Jordan River.\n\nHe was brave and spoke truth even to kings.\n\nHe invites us to prepare our heart to receive Jesus.",
  "Decir la verdad con amor es santo.",
  "Speaking truth with love is holy.",
  "Confiésate antes de Navidad o Pascua.",
  "Go to Confession before Christmas or Easter."),

S("sanmaximiliano","sanmaximiliano","sanmaximiliano.svg","#2a4a6a",
  "Maximiliano Kolbe","Maximilian Kolbe",
  "Dio su vida por un papá","He gave his life for a father",
  "En un campo de concentración, Maximiliano ofreció morir en lugar de otro padre de familia. Fue martir de la caridad.\n\nNos enseña el amor hasta el final.\n\nPodemos ser héroes en cosas pequeñas cada día.",
  "In a concentration camp, Maximilian offered to die instead of another father. He was a martyr of charity.\n\nHe teaches love to the end.\n\nWe can be heroes in small things each day.",
  "Amar es dar la vida por el otro.",
  "To love is to give life for another.",
  "Deja que otro elija primero en un juego.",
  "Let someone else choose first in a game."),

S("sanlorenzo","sanlorenzo","sanlorenzo.svg","#7a3a20",
  "San Lorenzo y los pobres","Saint Lawrence and the poor",
  "Entregó el tesoro de la Iglesia","He gave the Church's treasure",
  "Cuando le pidieron el oro de la Iglesia, Lorenzo presentó a los pobres: «Este es nuestro tesoro.»\n\nMurió valiente por su fe. Nos recuerda que las personas valen más que el dinero.",
  "When asked for the Church's gold, Lawrence presented the poor: \"This is our treasure.\"\n\nHe died bravely for his faith. He reminds us people are worth more than money.",
  "Los pobres son tesoro de Dios.",
  "The poor are God's treasure.",
  "Dona algo tuyo a quien lo necesite.",
  "Donate something of yours to someone in need."),

S("santaclara","santaclara","santaclara.svg","#8a6020",
  "Santa Clara y la Eucaristía","Saint Clare and the Eucharist",
  "El milagro del Santísimo","The miracle of the Blessed Sacrament",
  "Clara dejó riquezas para seguir a Francisco de Asís. Un día enemigos atacaron su convento. Ella mostró la Hostia y los enemigos huyeron.\n\nConfiaba que Jesús en la Eucaristía es más fuerte que cualquier miedo.\n\nVisita al Señor en la iglesia.",
  "Clare left wealth to follow Francis of Assisi. One day enemies attacked her convent. She showed the Host and they fled.\n\nShe trusted Jesus in the Eucharist is stronger than any fear.\n\nVisit the Lord in church.",
  "Jesús sacramentado es nuestra fortaleza.",
  "Jesus in the sacrament is our strength.",
  "Genuflecta con reverencia al pasar por el tabernáculo.",
  "Genuflect reverently when passing the tabernacle."),

S("santacatalina","santacatalina","santacatalina.svg","#5a1a8a",
  "Santa Catalina de Siena","Saint Catherine of Siena",
  "Una joven que habló con papas","A young woman who spoke with popes",
  "Catalina desde niña amaba a Jesús. Aunque no sabía leer mucho, Dios le dio sabiduría para ayudar a la Iglesia y a la paz.\n\nNos muestra que la edad no limita a Dios.",
  "Catherine loved Jesus from childhood. Though she did not read much, God gave her wisdom to help the Church and peace.\n\nShe shows age does not limit God.",
  "Dios puede usar tu voz.",
  "God can use your voice.",
  "Di algo bueno y verdadero hoy.",
  "Say something good and true today."),

S("lourdes","lourdes","lourdes.svg","#2f5f86",
  "Bernadette y Lourdes","Bernadette and Lourdes",
  "La niña que vio a la Virgen en una cueva","The girl who saw Mary in a cave",
  "Bernadette era pobre y enfermiza. La Virgen se le apareció en Lourdes y le pidió rezar por los pecadores.\n\nAllí muchos enfermos buscan sanación. María aparece a los pequeños.",
  "Bernadette was poor and sickly. Our Lady appeared to her at Lourdes and asked her to pray for sinners.\n\nThere many sick seek healing. Mary appears to the little ones.",
  "María cuida a los enfermos.",
  "Mary cares for the sick.",
  "Ora por enfermos del hospital.",
  "Pray for hospital patients."),

S("santarita","santarita","santarita.svg","#7a1520",
  "Santa Rita, la imposible","Saint Rita, the impossible",
  "Cuando todo parece sin solución","When everything seems hopeless",
  "Rita quiso ser monja pero tuvo una familia difícil. Después de muchos sufrimientos entró al convento.\n\nEs patrona de causas imposibles porque nunca dejó de confiar.\n\nPide su ayuda en problemas grandes.",
  "Rita wanted to be a nun but had a difficult family. After much suffering she entered the convent.\n\nShe is patron of impossible causes because she never stopped trusting.\n\nAsk her help in big problems.",
  "Con Dios no hay «imposible».",
  "With God there is no \"impossible.\"",
  "Escribe una intención difícil y entrégala a Dios.",
  "Write a hard intention and give it to God."),

S("santadymphna","santadymphna","santadymphna.svg","#4a2a7a",
  "Santa Dymphna y la paz interior","Saint Dymphna and inner peace",
  "Patrona de la salud mental","Patron of mental health",
  "Dymphna huyó de quien la quería hacer daño. Protegió su pureza y su fe. Hoy intercede por quien sufre en la mente y el corazón.\n\nPedir ayuda cuando estamos mal es valentía, no debilidad.",
  "Dymphna fled from one who wanted to harm her. She protected her purity and faith. Today she intercedes for those who suffer in mind and heart.\n\nAsking for help when we are unwell is courage, not weakness.",
  "Tu mente también importa a Dios.",
  "Your mind matters to God too.",
  "Si estás triste, habla con un adulto de confianza.",
  "If you are sad, talk to a trusted adult."),

S("sanfranciscojavier","sanfranciscojavier","sanfranciscojavier.svg","#3a5a4a",
  "Francisco Javier misionero","Francis Xavier the missionary",
  "Fue lejos a contar a Jesús","He went far to tell about Jesus",
  "Francisco Javier viajó a Asia en barco para evangelizar. Aprendió idiomas y bautizó miles.\n\nNos recuerda que la fe se comparte, no se guarda.\n\nTú puedes contar a Jesús a un amigo.",
  "Francis Xavier traveled to Asia by ship to evangelize. He learned languages and baptized thousands.\n\nHe reminds us faith is shared, not hoarded.\n\nYou can tell a friend about Jesus.",
  "Evangelizar es decir «Jesús te ama».",
  "Evangelizing is saying \"Jesus loves you.\"",
  "Invita a un amigo a Misa o grupo parroquial.",
  "Invite a friend to Mass or parish group."),

S("sanfranciscodesales","sanfranciscodesales","sanfranciscodesales.svg","#4a6a5a",
  "Francisco de Sales y la dulzura","Francis de Sales and gentleness",
  "Amable con las palabras","Gentle with words",
  "Francisco enseñó que la santidad es para todos, no solo monjes. Escribió cartas llenas de ternura.\n\nDecía que más moscas se cazan con miel que con vinagre.\n\nTus palabras pueden curar o herir.",
  "Francis taught holiness is for everyone, not only monks. He wrote letters full of tenderness.\n\nHe said more flies are caught with honey than vinegar.\n\nYour words can heal or hurt.",
  "Habla con dulzura.",
  "Speak with gentleness.",
  "Hoy solo di palabras buenas.",
  "Today only say kind words."),

S("sanjuanapostol","sanjuanapostol","sanjuanapostol.svg","#1a3a6a",
  "Juan, el apóstol del amor","John, the apostle of love",
  "El discípulo a quien Jesús amaba","The disciple whom Jesus loved",
  "Juan era joven y estaba junto a Jesús en la Última Cena. Escribió: «Dios es amor.»\n\nNos invita a amar como Jesús amó.\n\nSer el «amigo» de Jesús es posible.",
  "John was young and stood near Jesus at the Last Supper. He wrote: \"God is love.\"\n\nHe invites us to love as Jesus loved.\n\nBeing Jesus' \"friend\" is possible.",
  "Amar es el mandamiento más grande.",
  "Love is the greatest commandment.",
  "Haz un acto de amor concreto hoy.",
  "Do one concrete act of love today."),

S("sandaniel","sandaniel","sandaniel.svg","#5a4a20",
  "Daniel en el foso de los leones","Daniel in the lions' den",
  "Oró y Dios lo protegió","He prayed and God protected him",
  "Daniel rezaba tres veces al día aunque estaba prohibido. Lo echaron a un foso con leones, pero Dios cerró sus bocas.\n\nNos enseña a orar aunque otros se rían.\n\nDios protege a quien es fiel.",
  "Daniel prayed three times daily though it was forbidden. He was thrown to lions, but God shut their mouths.\n\nHe teaches us to pray even if others laugh.\n\nGod protects the faithful.",
  "Orar cada día fortalece el corazón.",
  "Praying daily strengthens the heart.",
  "Reza a la misma hora tres días seguidos.",
  "Pray at the same time three days in a row."),

S("reydavid","reydavid","reydavid.svg","#6a5020",
  "David y Goliat","David and Goliath",
  "Pequeño pero confiado en Dios","Small but trusting God",
  "David era joven y sin armadura. Enfrentó al gigante Goliat con una honda y fe en Dios.\n\nGanó porque confió en el Señor, no en su fuerza.\n\nTus «gigantes» también pueden caer con Dios.",
  "David was young and without armor. He faced giant Goliath with a sling and faith in God.\n\nHe won because he trusted the Lord, not his strength.\n\nYour \"giants\" can fall with God too.",
  "Con Dios, el pequeño puede vencer.",
  "With God, the small can win.",
  "Enfrenta un miedo con oración.",
  "Face a fear with prayer."),

S("sanefren","sanefren","sanefren.svg","#4a3a5a",
  "Efrén el siervo de María","Ephrem the servant of Mary",
  "Cantos para la Virgen","Songs for the Virgin",
  "Efrén escribió himnos hermosos para María y Jesús. Usaba la poesía para enseñar la fe.\n\nNos muestra que el arte también puede glorificar a Dios.\n\nPuedes cantar o dibujar para Jesús.",
  "Ephrem wrote beautiful hymns for Mary and Jesus. He used poetry to teach the faith.\n\nHe shows art can also glorify God.\n\nYou can sing or draw for Jesus.",
  "Tu talento es regalo de Dios.",
  "Your talent is God's gift.",
  "Canta o dibuja algo para Dios.",
  "Sing or draw something for God."),

S("santaapolonia","santaapolonia","santaapolonia.svg","#6a3a4a",
  "Santa Apolonia y el valor","Saint Apolonia and courage",
  "Valentía ante el sufrimiento","Courage before suffering",
  "Apolonia sufrió mucho por ser cristiana, pero no renunció a Jesús. Intercede por quien tiene dolor de dientes.\n\nNos recuerda que los mártires amaron a Dios más que la comodidad.",
  "Apolonia suffered much for being Christian but did not renounce Jesus. She intercedes for tooth pain.\n\nShe reminds us martyrs loved God more than comfort.",
  "El amor a Dios da fuerzas.",
  "Love of God gives strength.",
  "Ofrécele a Dios un pequeño sacrificio hoy.",
  "Offer God a small sacrifice today."),

S("santabarbara","santabarbara","santabarbara.svg","#8a1a1a",
  "Santa Bárbara y la tormenta","Saint Barbara and the storm",
  "Protección en peligro repentino","Protection in sudden danger",
  "Bárbara fue encerrada en una torre por su fe. Antes de morir pidió que quien invocara su nombre en peligro recibiera ayuda.\n\nMuchos mineros y soldados confían en ella.\n\nPide protección en viajes y tormentas.",
  "Barbara was locked in a tower for her faith. Before dying she asked that those who invoked her in danger receive help.\n\nMany miners and soldiers trust her.\n\nAsk protection in travels and storms.",
  "Dios cuida en el peligro.",
  "God cares in danger.",
  "Reza antes de una tormenta o viaje.",
  "Pray before a storm or trip."),

S("sanjuandedios","sanjuandedios","sanjuandedios.svg","#5a3040",
  "San Juan de Dios","Saint John of God",
  "De soldado a enfermero santo","From soldier to saint nurse",
  "Juan pasó por muchas aventuras hasta que entendió su vocación: cuidar enfermos. Fundó hospitales.\n\nNunca es tarde para empezar de nuevo con Dios.\n\nTu vida puede cambiar de rumbo.",
  "John went through many adventures until he understood his calling: care for the sick. He founded hospitals.\n\nIt is never too late to start anew with God.\n\nYour life can change direction.",
  "Siempre hay una nueva oportunidad.",
  "There is always a new chance.",
  "Pide perdón y empieza de nuevo hoy.",
  "Ask forgiveness and begin again today."),

S("juanpablo","juanpablo","juanpablo.svg","#2a3a5a",
  "Juan Pablo II y los jóvenes","John Paul II and youth",
  "«No tengáis miedo»","Do not be afraid",
  "Karol Wojtyla era joven durante la guerra. Se hizo sacerdote y papa. Repetía a millones de jóvenes: «No tengáis miedo. Abrid las puertas a Cristo.»\n\nCreía que los jóvenes pueden cambiar el mundo con santidad.",
  "Karol Wojtyla was young during the war. He became a priest and pope. He told millions of youth: \"Do not be afraid. Open the doors to Christ.\"\n\nHe believed youth can change the world with holiness.",
  "No tengas miedo de ser santo.",
  "Do not be afraid to be holy.",
  "Di: «Jesús, no tengo miedo de seguirte.»",
  "Say: \"Jesus, I am not afraid to follow You.\""),

S("sanbonifacio","sanbonifacio","sanbonifacio.svg","#3a4a2a",
  "San Bonifacio evangelizador","Saint Boniface the evangelizer",
  "Llevó la fe a nuevas tierras","He brought faith to new lands",
  "Bonifacio viajó a Germania para contar el Evangelio. Taló un roble sagrado pagano y construyó una capilla con la madera.\n\nSimboliza que la fe en Cristo es firme.\n\nComparte tu fe con valentía.",
  "Boniface traveled to Germany to preach the Gospel. He cut down a pagan sacred oak and built a chapel with the wood.\n\nIt symbolizes faith in Christ is firm.\n\nShare your faith bravely.",
  "Contar a Jesús es misión de todos.",
  "Telling about Jesus is everyone's mission.",
  "Explica a un amigo una oración que sabes.",
  "Teach a friend a prayer you know."),

S("sanbrendan","sanbrendan","sanbrendan.svg","#1a4a6a",
  "San Brendán navegante","Saint Brendan the navigator",
  "Aventura en el mar con fe","Adventure on the sea with faith",
  "Breandán fue monje irlandés que navegó el océano con monjes buscando la «tierra prometida de los santos».\n\nNos invita a explorar el mundo confiando en Dios.\n\nCada viaje puede ser peregrinación.",
  "Brendan was an Irish monk who sailed the ocean with monks seeking the \"promised land of saints.\"\n\nHe invites us to explore the world trusting God.\n\nEvery journey can be a pilgrimage.",
  "Explorar también puede ser oración.",
  "Exploring can also be prayer.",
  "Da gracias por un lugar bonito que viste.",
  "Give thanks for a beautiful place you saw."),

S("santotomas","santotomasdeaquino","santotomasdeaquino.svg","#4a3a2a",
  "Tomás de Aquino, el estudiante santo","Thomas Aquinas, the holy student",
  "Preguntar también es buscar a Dios","Asking questions is seeking God",
  "Tomás era muy inteligente y amaba estudiar la fe. Escribió libros para entender mejor a Dios.\n\nNos enseña que estudiar con honestidad también es santo.\n\nHaz bien tus tareas como ofrenda a Dios.",
  "Thomas was very intelligent and loved studying faith. He wrote books to understand God better.\n\nHe teaches studying honestly is also holy.\n\nDo your homework well as an offering to God.",
  "Estudiar bien honra a Dios.",
  "Studying well honors God.",
  "Estudia hoy con esfuerzo y oración.",
  "Study today with effort and prayer."),

S("sangerardo","sangerardo","sangerardo.svg","#5a2a3a",
  "San Gerardo y las mamás","Saint Gerard and mothers",
  "Patrono de embarazadas","Patron of expectant mothers",
  "Gerardo ayudó a familias pobres y protegió a madres embarazadas. Fue conocido por su bondad.\n\nIntercede por bebés y mamás.\n\nOra por las familias que esperan un hijo.",
  "Gerard helped poor families and protected expectant mothers. He was known for kindness.\n\nHe intercedes for babies and moms.\n\nPray for families expecting a child.",
  "La vida del bebé es un regalo.",
  "A baby's life is a gift.",
  "Ora por un bebé que va a nacer.",
  "Pray for a baby about to be born."),

S("sanmartindelporres","sanmartindelporres","sanmartin.svg","#4a3020",
  "Martín de Porres","Martin de Porres",
  "El hermano de todos","Brother of all",
  "Martín era mulato y enfrentó discriminación. Cuidó enfermos, animales y pobres en Lima. Decían que hablaba con perros y ratones para que no pelearan.\n\nNos enseña respeto a todos, sin importar el color.",
  "Martin was mixed-race and faced discrimination. He cared for sick, animals, and poor in Lima. They say he talked to dogs and mice so they would not fight.\n\nHe teaches respect for all, regardless of color.",
  "Todos somos hermanos ante Dios.",
  "We are all brothers and sisters before God.",
  "Trata bien a alguien diferente a ti.",
  "Treat someone different from you with kindness."),

S("santarosa","santarosa","santarosa.svg","#8a2050",
  "Rosa de Lima","Rose of Lima",
  "Primera santa de América","First saint of the Americas",
  "Rosa amaba a Jesús desde niña en Perú. Cuidaba enfermos y jardín. Ofreció su sufrimiento por las almas.\n\nNos recuerda que América Latina tiene santos desde hace siglos.",
  "Rose loved Jesus from childhood in Peru. She cared for sick and garden. She offered suffering for souls.\n\nShe reminds us Latin America has saints for centuries.",
  "Tu país también tiene santos.",
  "Your country has saints too.",
  "Busca un santo de tu país.",
  "Look up a saint from your country."),

S("misericordia","misericordia","misericordia.svg","#a01818",
  "Jesús Misericordioso","Divine Mercy",
  "«Jesús, en Ti confío»","Jesus, I trust in You",
  "Jesús se apareció a Santa Faustina y pidió confiar en su misericordia. Dijo que el rayo rojo y blanco significa sangre y agua que salvan.\n\nA las tres de la tarde podemos recordar su muerte y amor.\n\nDi: «Jesús, en Ti confío.»",
  "Jesus appeared to Saint Faustina and asked trust in His mercy. He said the red and white rays mean blood and water that save.\n\nAt three in the afternoon we can remember His death and love.\n\nSay: \"Jesus, I trust in You.\"",
  "La misericordia es más grande que el pecado.",
  "Mercy is greater than sin.",
  "Di tres veces: «Jesús, en Ti confío.»",
  "Say three times: \"Jesus, I trust in You.\""),

S("sagradocorazon","sagradocorazon","sagradocorazon.svg","#7a1515",
  "El Sagrado Corazón","The Sacred Heart",
  "El corazón de Jesús en llamas de amor","Jesus' heart burning with love",
  "El Sagrado Corazón muestra el amor ardiente de Jesús por nosotros. Latía por la humanidad y por cada niño.\n\nJunio es mes del Sagrado Corazón. Podemos consolarlo amando y obedeciendo.\n\nJesús te ama con todo su corazón.",
  "The Sacred Heart shows Jesus' burning love for us. It beat for humanity and every child.\n\nJune is the month of the Sacred Heart. We can console Him by loving and obeying.\n\nJesus loves you with all His heart.",
  "El amor de Jesús nunca se apaga.",
  "Jesus' love never goes out.",
  "Haz una buena acción en reparación.",
  "Do a good deed in reparation."),

S("angelguarda","angelguarda","ninos-angel.svg","#4a4a70",
  "Tu ángel te acompaña","Your angel goes with you",
  "No caminas solo","You do not walk alone",
  "Cada persona tiene un ángel de la guarda desde que nace. Te cuida en el colegio, en el juego y de noche.\n\nJesús dijo que los ángeles de los niños siempre ven la cara del Padre.\n\nSaluda a tu ángel cada mañana.",
  "Each person has a guardian angel from birth. They watch over you at school, play, and at night.\n\nJesus said children's angels always see the Father's face.\n\nGreet your angel every morning.",
  "Tu ángel es tu amigo invisible.",
  "Your angel is your invisible friend.",
  "Reza el Ángel de la Guarda antes de dormir.",
  "Pray the Guardian Angel prayer before sleep."),

S("schoenstatt","schoenstatt","schoenstatt.svg","#1a3070",
  "María de Schoenstatt","Our Lady of Schoenstatt",
  "Un santuario pequeño, un corazón grande","A small shrine, a big heart",
  "En Alemania, jóvenes consagraron un pequeño santuario a María. Desde ahí nació un movimiento de familias y niños.\n\nMaría quiere formar hogares llenos de amor y fe.\n\nPuedes tener un rincón de oración en casa.",
  "In Germany, youth consecrated a small shrine to Mary. From there a movement of families and children grew.\n\nMary wants to form homes full of love and faith.\n\nYou can have a prayer corner at home.",
  "María cuida las familias.",
  "Mary cares for families.",
  "Arma un rincón con cruz o imagen de María.",
  "Set up a corner with a cross or image of Mary."),

S("santacoleta","santacoleta","santacoleta.svg","#6a4a6a",
  "Santa Coleta y la paz","Saint Colette and peace",
  "Reformó con ternura","She reformed with tenderness",
  "Coleta era francesa y quiso reformar su orden con paz y oración. Confió en Dios en tiempos difíciles.\n\nNos enseña que los cambios buenos empiezan en el corazón.",
  "Colette was French and wanted to reform her order with peace and prayer. She trusted God in hard times.\n\nShe teaches good change begins in the heart.",
  "La paz empieza en ti.",
  "Peace begins in you.",
  "Pide perdón si peleaste con alguien.",
  "Ask forgiveness if you fought with someone."),

S("santaemma","santaemma","santaemma.svg","#8a2a5a",
  "Santa Emma y el duelo","Saint Emma and grief",
  "Consuelo para los que lloran","Comfort for those who weep",
  "Emma perdió a su esposo e hijos pero no perdió la fe. Usó su riqueza para ayudar a pobres y construir iglesias.\n\nIntercede por quienes están tristes por una pérdida.\n\nDios abraza a los que lloran.",
  "Emma lost husband and children but not her faith. She used wealth to help poor and build churches.\n\nShe intercedes for those sad from loss.\n\nGod embraces those who weep.",
  "Dios está cerca de los tristes.",
  "God is close to the sad.",
  "Abraza a alguien que está triste.",
  "Hug someone who is sad."),

S("santanoemi","santanoemi","santanoemi.svg","#5a6a4a",
  "Santa Noemí y la familia","Saint Naomi and family",
  "Lealtad y cuidado","Loyalty and care",
  "En la Biblia, Noemí perdió mucho pero su nuera Rut no la abandonó. Juntas confiaron en Dios.\n\nNos enseña lealtad familiar y esperanza.\n\nCuida a quienes son familia para ti.",
  "In the Bible, Naomi lost much but her daughter-in-law Ruth did not leave her. Together they trusted God.\n\nShe teaches family loyalty and hope.\n\nCare for those who are family to you.",
  "La familia se cuida mutuamente.",
  "Family cares for one another.",
  "Ayuda a un familiar hoy.",
  "Help a family member today."),

S("sanmartin","sanmartin","sanmartin.svg","#3a3020",
  "San Martín y el mendigo","Saint Martin and the beggar",
  "Partió su capa por amor","He split his cloak in love",
  "Martín era soldado. Vio a un pobre con frío y partió su capa por la mitad. Esa noche soñó con Jesús vestido con la mitad de la capa.\n\nNos enseña que servir al pobre es servir a Cristo.",
  "Martin was a soldier. He saw a poor man cold and split his cloak in half. That night he dreamed of Jesus wearing half the cloak.\n\nHe teaches serving the poor is serving Christ.",
  "Lo que haces al pobre lo haces a Jesús.",
  "What you do to the poor you do to Jesus.",
  "Comparte abrigo o comida con quien lo necesite.",
  "Share a coat or food with someone in need."),
]

# Fix duplicate sanmartin id - last one should be sanmartin (cape story) - remove duplicate sanmartindelporres if we have two sanmartin
# Check: we have sanmartin twice - sanmartindelporres and sanmartin cape. Fix ids.
for c in CUENTOS:
    if c["id"] == "sanmartin" and "mendigo" in c["title"]["es"]:
        c["id"] = "sanmartincapa"
        c["saintId"] = "sanmartin"

# Deduplicate by id keeping first
seen = set()
unique = []
for c in CUENTOS:
    if c["id"] in seen:
        continue
    seen.add(c["id"])
    unique.append(c)

# Expand to calm bedtime-length stories
for c in unique:
    es_long, en_long, read_min = expand_bedtime(
        c["story"]["es"],
        c["story"]["en"],
        c["title"]["es"],
        c["title"]["en"],
        c["moral"]["es"],
        c["moral"]["en"],
        c["id"],
    )
    c["story"] = {"es": es_long, "en": en_long}
    c["readMin"] = read_min
    c["bedtime"] = True

OUT.write_text(json.dumps({"cuentos": unique}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"Wrote {len(unique)} bedtime cuentos to {OUT}")
