# -*- coding: utf-8 -*-
import json, os

data = {
  "id": "santagema",
  "name": {
    "es": "Santa Gema Galgani",
    "en": "Saint Gemma Galgani"
  },
  "feast_day": {
    "es": "11 de abril",
    "en": "April 11"
  },
  "image": "/assets/images/santagema.svg",
  "prayer": {
    "es": "Oh Santa Gema, que viviste con el dolor como compañero permanente y lo transformaste en amor, hoy me acerco a ti desde mi propio sufrimiento.\n\nTú sabes lo que es despertar cada día con dolor. Tú sabes lo que es que los médicos no encuentren respuesta, lo que es que el cuerpo no obedezca y que el sufrimiento no tenga nombre reconocible. Tú viviste con la tuberculosis que destruía tu columna, con los estigmas que te hacían sangrar, con la presencia de lo sobrenatural mezclada con lo ordinario del dolor físico.\n\nTe encomiendo a (nombra al que sufre: una persona con dolor crónico, fibromialgia, dolor de espalda, enfermedad sin diagnóstico, sufrimiento que no cesa). Que ese dolor no aplaste la fe ni apague la esperanza.\n\nY te pido algo más: que quien sufre encuentre en el sufrimiento no solo tormento sino también un camino hacia Dios, como tú lo encontraste. No porque el dolor sea bueno, sino porque Dios puede hacer algo bueno incluso en él.\n\nSanta Gema, amiga de Dios en el sufrimiento, ruega por nosotros. Amén.",
    "en": "O Saint Gemma, you lived with pain as a constant companion and transformed it into love. Today I come to you from my own suffering.\n\nYou know what it is to wake up every day in pain. You know what it is when doctors find no answer, when the body does not obey and the suffering has no recognizable name. You lived with tuberculosis destroying your spine, with the stigmata that made you bleed, with the presence of the supernatural intermingled with the ordinary reality of physical pain.\n\nI entrust to you (name the one who suffers: a person with chronic pain, fibromyalgia, back pain, an undiagnosed illness, unceasing suffering). May that pain not crush faith or extinguish hope.\n\nAnd I ask something more: may whoever suffers find in suffering not only torment but also a path toward God, as you found it. Not because pain is good, but because God can do something good even within it.\n\nSaint Gemma, friend of God in suffering, pray for us. Amen."
  },
  "history": {
    "es": "Gema Galgani nació en Camigliano, cerca de Lucca, en la Toscana italiana, el 12 de marzo de 1878. Fue la quinta de ocho hijos. Su infancia estuvo marcada por la enfermedad y la pérdida: su madre murió de tuberculosis cuando Gema tenía siete años, y ella misma comenzó a mostrar síntomas de la misma enfermedad desde pequeña.\n\nA los dieciocho años sufrió una enfermedad gravísima que los médicos no supieron tratar: una caries tuberculosa de la columna vertebral que la dejó paralizada. La parálisis fue completa durante meses. Según su testimonio y el de sus biógrafos, se encomendó al Beato Gabriel de la Dolorosa —un pasionista que había muerto joven en olor de santidad— y recuperó el uso de sus piernas de manera que el médico que la trataba, un agnóstico convencido llamado Dr. Pfanner, reconoció como inexplicable desde el punto de vista médico.\n\nA partir de 1899, Gema comenzó a experimentar los estigmas: las llagas de la Pasión de Cristo en sus manos, pies y costado, que se abrían con regularidad los jueves por la noche y cerraban el viernes. Vivió este fenómeno con terror al principio, luego con aceptación, y siempre en obediencia a sus directores espirituales, que los investigaron con rigor. El padre Germán Ruoppolo, pasionista, fue su director espiritual y documentó estos fenómenos en detalle.\n\nGema vivió con una familia de Lucca, los Giannini, que la acogieron como hija. Era analfabeta en teología pero sus cartas espirituales, conservadas íntegramente, muestran una profundidad mística que sus directores espirituales reconocieron como extraordinaria. Escribía sobre el sufrimiento con una lucidez que no venía de los libros.\n\nMurió de tuberculosis el 11 de abril de 1903, a los veinticinco años. Su última palabra, según los presentes, fue el nombre de Jesús. Fue beatificada en 1933 y canonizada en 1940. Es patrona de los enfermos de espalda, de quienes padecen dolor crónico, de las personas con tuberculosis y de los farmacéuticos.",
    "en": "Gemma Galgani was born in Camigliano, near Lucca, in Tuscany, Italy, on March 12, 1878. She was the fifth of eight children. Her childhood was marked by illness and loss: her mother died of tuberculosis when Gemma was seven, and she herself began showing symptoms of the same disease from an early age.\n\nAt eighteen she suffered a grave illness that doctors could not treat: tuberculous disease of the spine that left her paralyzed. The paralysis was complete for months. According to her testimony and that of her biographers, she entrusted herself to Blessed Gabriel of Our Lady of Sorrows — a Passionist who had died young in the odor of sanctity — and recovered the use of her legs in a manner that the doctor treating her, a convinced agnostic named Dr. Pfanner, acknowledged as medically inexplicable.\n\nFrom 1899, Gemma began experiencing the stigmata: the wounds of Christ's Passion in her hands, feet, and side, which regularly opened on Thursday nights and closed on Fridays. She lived this phenomenon with terror at first, then with acceptance, always in obedience to her spiritual directors, who investigated it rigorously. Father Germán Ruoppolo, a Passionist, was her spiritual director and documented these phenomena in detail.\n\nGemma lived with a family in Lucca, the Gianninis, who took her in as a daughter. She was theologically unlearned, but her spiritual letters, preserved in their entirety, show a mystical depth that her spiritual directors recognized as extraordinary. She wrote about suffering with a lucidity that did not come from books.\n\nShe died of tuberculosis on April 11, 1903, at the age of twenty-five. Her last word, according to those present, was the name of Jesus. She was beatified in 1933 and canonized in 1940. She is the patron of those with back pain, of those who suffer from chronic pain, of people with tuberculosis, and of pharmacists."
  },
  "novena_prayers": {
    "es": "Novena a Santa Gema Galgani — Modo de rezar\n\nCada día durante 9 días:\n1. Señal de la Cruz\n2. Padre Nuestro, Ave María, Gloria\n3. Oración propia del día (ver abajo)\n4. Jaculatoria: «Santa Gema, que en el dolor encontraste a Cristo, ruega por nosotros.» (3 veces)\n\nEspecialmente recomendada para: personas con dolor crónico, fibromialgia, dolor de espalda, enfermedades sin diagnóstico, cuidadores de enfermos crónicos.",
    "en": "Novena to Saint Gemma Galgani — How to Pray\n\nEach day for 9 days:\n1. Sign of the Cross\n2. Our Father, Hail Mary, Glory Be\n3. Prayer of the day (see below)\n4. Aspiration: 'Saint Gemma, who found Christ in suffering, pray for us.' (3 times)\n\nEspecially recommended for: people with chronic pain, fibromyalgia, back pain, undiagnosed illnesses, caregivers of the chronically ill."
  },
  "novena": [
    {
      "day": 1,
      "es": "Día 1 — El dolor sin nombre\n\nSanta Gema, tú sufriste enfermedades que los médicos no entendían, y además los fenómenos místicos que te hacían sangrar y que muchos miraban con desconfianza. Conoces el dolor que no tiene diagnóstico, el que nadie termina de creer. Hoy intercede por todos los que sufren así: que sean escuchados, que sean creídos, y que encuentren médicos con paciencia.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 1 — The pain with no name\n\nSaint Gemma, you suffered from illnesses that doctors did not understand, and also from mystical phenomena that made you bleed and that many viewed with distrust. You know pain that has no diagnosis, pain that no one quite believes. Today intercede for all who suffer this way: may they be heard, believed, and find patient doctors.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 2,
      "es": "Día 2 — La columna y la espalda\n\nSanta Gema, patrona de los enfermos de espalda, la tuberculosis destruyó tu columna vertebral y quedaste paralizada. Hoy te encomiendo a todos los que sufren en la espalda: hernias, ciáticas, escoliosis, fracturas, dolor crónico sin causa visible. Intercede para que encuentren alivio y que los tratamientos sean eficaces.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 2 — The spine and back\n\nSaint Gemma, patron of back sufferers, tuberculosis destroyed your spine and you were left paralyzed. Today I entrust to you all who suffer in their backs: hernias, sciatica, scoliosis, fractures, chronic pain without visible cause. Intercede so that they find relief and that treatments prove effective.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 3,
      "es": "Día 3 — El sufrimiento como misterio\n\nSanta Gema, tú aceptaste el sufrimiento no porque lo entendieras sino porque confiabas en Quien te lo pedía. Hoy te pido esa misma confianza para quienes sufren sin encontrar sentido. Que cuando no haya respuesta al «¿por qué?» haya al menos la certeza del «Alguien te sostiene».\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 3 — Suffering as mystery\n\nSaint Gemma, you accepted suffering not because you understood it but because you trusted the One who asked it of you. Today I ask for that same trust for those who suffer without finding meaning. May when there is no answer to the 'why?' there at least be the certainty of 'Someone is holding you.'\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 4,
      "es": "Día 4 — Los estigmas y las llagas de Cristo\n\nSanta Gema, los estigmas que recibiste te hacían participar físicamente en la Pasión de Cristo. Hoy te encomiendo a todos los que tienen heridas que no cierran: heridas físicas que no sanan, úlceras, llagas. Que Dios que curó tus llagas interceda también por las de ellos.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 4 — The stigmata and the wounds of Christ\n\nSaint Gemma, the stigmata you received made you physically participate in the Passion of Christ. Today I entrust to you all those who have wounds that do not close: physical wounds that do not heal, ulcers, sores. May the God who healed your wounds intercede also for theirs.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 5,
      "es": "Día 5 — La fibromialgia y el dolor crónico\n\nSanta Gema, tu dolor era constante y no siempre tenía causa visible. Hoy te encomiendo especialmente a los que sufren fibromialgia, síndrome de fatiga crónica, dolor difuso sin diagnóstico claro. Que sean tomados en serio. Que encuentren alivio. Que no estén solos en esto.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 5 — Fibromyalgia and chronic pain\n\nSaint Gemma, your pain was constant and not always visibly caused. Today I entrust to you especially those who suffer from fibromyalgia, chronic fatigue syndrome, diffuse pain without clear diagnosis. May they be taken seriously. May they find relief. May they not be alone in this.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 6,
      "es": "Día 6 — Las cartas de Gema: la voz del que no puede salir\n\nSanta Gema, desde tu habitación escribiste cartas que hoy forman parte del patrimonio espiritual de la Iglesia. Tú encontraste en la escritura una manera de dar lo que no podías dar físicamente. Hoy te encomiendo a todos los enfermos crónicos que sienten que su vida ya no puede aportar nada. Que encuentren en la oración y en el amor su propia manera de dar.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 6 — Gemma's letters: the voice of those who cannot go out\n\nSaint Gemma, from your room you wrote letters that today form part of the spiritual heritage of the Church. You found in writing a way to give what you could not give physically. Today I entrust to you all chronically ill people who feel their life can no longer contribute anything. May they find in prayer and love their own way of giving.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 7,
      "es": "Día 7 — Los cuidadores\n\nSanta Gema, la familia Giannini te cuidó con amor durante años, sin esperar nada a cambio. Hoy te encomiendo a todos los cuidadores de enfermos crónicos: los que llevan años acompañando a un familiar que no mejora. Que tengan paciencia renovada, que no se sientan solos, que sean vistos y valorados.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 7 — The caregivers\n\nSaint Gemma, the Giannini family cared for you with love for years, expecting nothing in return. Today I entrust to you all caregivers of the chronically ill: those who have spent years accompanying a family member who does not improve. May they have renewed patience, may they not feel alone, may they be seen and valued.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 8,
      "es": "Día 8 — El miedo a la muerte joven\n\nSanta Gema, moriste a los veinticinco años. No pudiste hacer lo que quizás soñaste: entrar en convento, criar hijos, envejecer. Hoy te encomiendo a todos los que enfrentan una enfermedad grave siendo jóvenes: el miedo a una vida interrumpida, el dolor de lo no vivido. Que encuentren la paz que tú encontraste.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 8 — The fear of dying young\n\nSaint Gemma, you died at twenty-five. You could not do what you perhaps dreamed: enter a convent, raise children, grow old. Today I entrust to you all who face grave illness while young: the fear of an interrupted life, the pain of the unlived. May they find the peace you found.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 9,
      "es": "Día 9 — «Jesús»: la última palabra\n\nSanta Gema, tu última palabra fue «Jesús». Que esa misma palabra sea la última de los que hoy están en el umbral. Y para los que todavía tienen tiempo: que aprendan a pronunciarla también hoy, no como fórmula sino como encuentro.\n\n«Santa Gema, que en el dolor encontraste a Cristo, ruega por nosotros.» (3 veces)\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 9 — 'Jesus': the last word\n\nSaint Gemma, your last word was 'Jesus.' May that same word be the last word of those now at the threshold. And for those who still have time: may they learn to speak it today as well, not as a formula but as an encounter.\n\n'Saint Gemma, who found Christ in suffering, pray for us.' (3 times)\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    }
  ],
  "chaplet": {
    "available": False,
    "es": "",
    "en": ""
  },
  "litany": {
    "available": True,
    "es": "Letanía a Santa Gema Galgani\n\nSeñor, ten piedad. Cristo, ten piedad. Señor, ten piedad.\nCristo, escúchanos. Cristo, óyenos.\nDios Padre celestial, ten misericordia de nosotros.\nDios Hijo Redentor del mundo, ten misericordia de nosotros.\nDios Espíritu Santo, ten misericordia de nosotros.\nSantísima Trinidad, un solo Dios, ten misericordia de nosotros.\n\nSanta Gema, virgen y mística, ruega por nosotros.\nSanta Gema, que recibiste los estigmas de Cristo, ruega por nosotros.\nSanta Gema, que soportaste la tuberculosis con fe, ruega por nosotros.\nSanta Gema, patrona de los enfermos de espalda, ruega por nosotros.\nSanta Gema, consolación de los que sufren dolor crónico, ruega por nosotros.\nSanta Gema, que curaste milagrosamente de la parálisis, ruega por nosotros.\nSanta Gema, que escribiste cartas de profundidad mística, ruega por nosotros.\nSanta Gema, cuya última palabra fue el nombre de Jesús, ruega por nosotros.\nSanta Gema, gloria de la Toscana, ruega por nosotros.\nSanta Gema, amiga de Dios en el sufrimiento, ruega por nosotros.\n\nCordero de Dios, que quitas el pecado del mundo, perdónanos, Señor.\nCordero de Dios, que quitas el pecado del mundo, escúchanos, Señor.\nCordero de Dios, que quitas el pecado del mundo, ten misericordia de nosotros.\n\nV. Ruega por nosotros, Santa Gema,\nR. Para que seamos dignos de alcanzar las promesas de Jesucristo.\n\nOremos: Oh Dios, que concediste a Santa Gema la gracia de compartir los sufrimientos de Tu Hijo y de encontrar en ellos la alegría, concédenos por su intercesión aceptar nuestros propios sufrimientos con fe y amor. Por Jesucristo Nuestro Señor. Amén.",
    "en": "Litany to Saint Gemma Galgani\n\nLord, have mercy. Christ, have mercy. Lord, have mercy.\nChrist, hear us. Christ, graciously hear us.\nGod the Father in heaven, have mercy on us.\nGod the Son, Redeemer of the world, have mercy on us.\nGod the Holy Spirit, have mercy on us.\nHoly Trinity, one God, have mercy on us.\n\nSaint Gemma, virgin and mystic, pray for us.\nSaint Gemma, who received the stigmata of Christ, pray for us.\nSaint Gemma, who bore tuberculosis with faith, pray for us.\nSaint Gemma, patron of back sufferers, pray for us.\nSaint Gemma, consolation of those with chronic pain, pray for us.\nSaint Gemma, who were miraculously healed of paralysis, pray for us.\nSaint Gemma, who wrote letters of mystical depth, pray for us.\nSaint Gemma, whose last word was the name of Jesus, pray for us.\nSaint Gemma, glory of Tuscany, pray for us.\nSaint Gemma, friend of God in suffering, pray for us.\n\nLamb of God, who takes away the sins of the world, spare us, O Lord.\nLamb of God, who takes away the sins of the world, graciously hear us, O Lord.\nLamb of God, who takes away the sins of the world, have mercy on us.\n\nV. Pray for us, Saint Gemma,\nR. That we may be made worthy of the promises of Christ.\n\nLet us pray: O God, who granted Saint Gemma the grace to share in the sufferings of Your Son and to find joy within them, grant us through her intercession to accept our own sufferings with faith and love. Through Christ our Lord. Amen."
  },
  "miracles": {
    "available": True,
    "es": "1. LA CURACIÓN MILAGROSA DE LA PARÁLISIS ESPINAL\nEl caso más documentado de la vida de Santa Gema es su curación de la caries tuberculosa de la columna vertebral. En 1899, después de que los médicos la desahuciaron, Gema rezó al Beato Gabriel de la Dolorosa durante nueve días. Al final de la novena, según los testimonios de los presentes y el reconocimiento posterior del médico que la trataba, Dr. Pfanner —un hombre que se declaraba agnóstico— recuperó completamente el uso de las piernas. El Dr. Pfanner declaró públicamente no tener explicación médica para lo ocurrido. Este caso fue examinado en el proceso de beatificación y contribuyó decisivamente a su causa.\n\n2. LOS ESTIGMAS DOCUMENTADOS POR DIRECTORES ESPIRITUALES RIGUROSOS\nLos estigmas de Gema fueron observados directamente por el Padre Germán Ruoppolo, pasionista, y por varios médicos que los examinaron a petición de la Iglesia. Las llagas aparecían regularmente los jueves por la noche, sangraban copiosamente durante el viernes y cerraban sin cicatriz para el sábado. Los médicos que los examinaron en vida de Gema no encontraron explicación natural a este ciclo. La Iglesia lo reconoció en el proceso canónico como uno de los elementos extraordinarios de su vida.\n\n3. CURACIONES ATRIBUIDAS A SU INTERCESIÓN DESPUÉS DE SU MUERTE\nDesde su muerte en 1903 y especialmente tras su beatificación y canonización, numerosas personas han reportado alivio de dolores de espalda crónicos, curas de tuberculosis en sus etapas iniciales, y recuperaciones de enfermedades neurológicas de la columna, atribuidas a la intercesión de Santa Gema. La Basílica de Santa Gema en Lucca mantiene un registro de estas gracias recibidas por peregrinos de todo el mundo.",
    "en": "1. THE MIRACULOUS HEALING FROM SPINAL PARALYSIS\nThe most documented case in Saint Gemma's life is her healing from tuberculous disease of the spine. In 1899, after doctors gave up on her, Gemma prayed to Blessed Gabriel of Our Lady of Sorrows for nine days. At the end of the novena, according to witnesses and the subsequent acknowledgment of the doctor treating her, Dr. Pfanner — a man who declared himself agnostic — she fully recovered the use of her legs. Dr. Pfanner publicly declared he had no medical explanation for what had occurred. This case was examined in the beatification process and contributed decisively to her cause.\n\n2. THE STIGMATA DOCUMENTED BY RIGOROUS SPIRITUAL DIRECTORS\nGemma's stigmata were directly observed by Father Germán Ruoppolo, a Passionist, and by several doctors who examined them at the Church's request. The wounds appeared regularly on Thursday nights, bled copiously throughout Friday, and closed without scar by Saturday. The doctors who examined them during Gemma's lifetime found no natural explanation for this cycle. The Church recognized this in the canonical process as one of the extraordinary elements of her life.\n\n3. HEALINGS ATTRIBUTED TO HER INTERCESSION AFTER DEATH\nSince her death in 1903, and especially after her beatification and canonization, numerous people have reported relief from chronic back pain, cures from tuberculosis in its early stages, and recoveries from neurological diseases of the spine, attributed to Saint Gemma's intercession. The Basilica of Saint Gemma in Lucca maintains a register of these graces received by pilgrims from around the world."
  }
}

out_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'santagema.json')
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print('santagema.json creado OK')
