import json, pathlib

data = {
  "id": "sanaxayacatl",
  "name": { "es": "San Axayacatl", "en": "Saint Axayacatl" },
  "feast_day": { "es": "Sin fecha fija en el calendario romano", "en": "No fixed date in the Roman calendar" },
  "image": "/assets/images/sanaxayacatl.svg",
  "prayer": {
    "es": "San Axayacatl, cuyo nombre en náhuatl significa 'cara de agua' —reflejo vivo del cielo— intercede por todos los que llevan este hermoso nombre de herencia indígena. Tú que uniste en tu nombre las raíces de la tierra con la fe en el Dios creador de los cielos y las aguas, ayúdanos a honrar nuestra herencia con gratitud y a vivir como hijos fieles de Dios. Que quienes portan tu nombre sean reflejo de Cristo en el mundo, como el agua que refleja el cielo. Amén.",
    "en": "Saint Axayacatl, whose name in Nahuatl means 'face of water'—a living reflection of the sky—intercede for all who bear this beautiful name of indigenous heritage. You who united in your name the roots of the earth with faith in the God who creates the heavens and the waters, help us to honor our heritage with gratitude and to live as faithful children of God. May those who bear your name be a reflection of Christ in the world, like water that mirrors the sky. Amen."
  },
  "history": {
    "es": "Axayacatl es un nombre de profunda raíz náhuatl que significa 'cara de agua' o 'el que tiene cara como el agua', evocando la imagen del cielo reflejado en la superficie de un lago. En la cosmovisión del pueblo náhuatl, el agua era elemento sagrado: fuente de vida, purificación y conexión con lo divino. Con la llegada del Evangelio a las tierras de Mesoamérica, muchos nombres indígenas fueron incorporados a la fe cristiana, dando lugar a una espiritualidad inculturada que honra tanto las raíces de los pueblos como la fe en Cristo. La Iglesia en México y en toda América Latina ha reconocido la riqueza espiritual de los pueblos originarios y su apertura al Dios vivo que los misioneros proclamaron. San Axayacatl representa a todos los bautizados que llevan nombres de herencia indígena, recordándonos que cada cultura contiene semillas del Verbo y que la fe cristiana no destruye las identidades sino que las eleva y las redime. Su nombre invita a contemplar a Dios como el cielo que se refleja en las aguas de nuestro bautismo.",
    "en": "Axayacatl is a name of deep Nahuatl origin meaning 'face of water' or 'one whose face is like water,' evoking the image of the sky reflected on the surface of a lake. In the worldview of the Nahuatl people, water was a sacred element: source of life, purification, and connection with the divine. With the arrival of the Gospel in the lands of Mesoamerica, many indigenous names were incorporated into Christian faith, giving rise to an inculturated spirituality that honors both the roots of peoples and faith in Christ. The Church in Mexico and throughout Latin America has recognized the spiritual richness of the indigenous peoples and their openness to the living God proclaimed by the missionaries. Saint Axayacatl represents all the baptized who bear names of indigenous heritage, reminding us that every culture contains seeds of the Word and that Christian faith does not destroy identities but elevates and redeems them. His name invites us to contemplate God as the sky reflected in the waters of our baptism."
  },
  "novena_prayers": {
    "es": "Señor Dios, creador del cielo y de las aguas: por la intercesión de San Axayacatl, bendice a todos los que llevan este nombre y a quienes honran su herencia indígena en la fe. Que encuentren en Cristo la plenitud de todo lo que la sabiduría de sus ancestros buscaba. Amén.",
    "en": "Lord God, creator of sky and waters: through the intercession of Saint Axayacatl, bless all who bear this name and those who honor their indigenous heritage in faith. May they find in Christ the fullness of all that the wisdom of their ancestors sought. Amen."
  },
  "novena": [
    { "day": 1, "es": "San Axayacatl, imagen del cielo en el agua: ayúdame a reflejar en mi vida la bondad y la luz de Dios, como el agua tranquila refleja el firmamento.", "en": "Saint Axayacatl, image of sky in water: help me to reflect in my life the goodness and light of God, as still water mirrors the heavens." },
    { "day": 2, "es": "San Axayacatl, puente entre herencias: intercede por todos los que buscan integrar su identidad indígena y su fe cristiana sin sentir contradicción, sino armonía.", "en": "Saint Axayacatl, bridge between heritages: intercede for all who seek to integrate their indigenous identity and Christian faith without contradiction, but in harmony." },
    { "day": 3, "es": "San Axayacatl, cuyo nombre honra el agua sagrada: ruega por todos los bautizados, especialmente los que llevan nombres indígenas, para que vivan plenamente su vocación cristiana.", "en": "Saint Axayacatl, whose name honors sacred water: pray for all the baptized, especially those who bear indigenous names, that they may fully live their Christian vocation." },
    { "day": 4, "es": "San Axayacatl, intercesor de los pueblos indígenas: ruega por la dignidad y los derechos de todos los pueblos originarios de América, para que sean respetados y evangelizados con amor.", "en": "Saint Axayacatl, intercessor of indigenous peoples: pray for the dignity and rights of all the original peoples of the Americas, that they may be respected and evangelized with love." },
    { "day": 5, "es": "San Axayacatl, cuyo nombre lleva la memoria de los ancestros: ayúdame a honrar a mis mayores con gratitud y a transmitir a mis hijos tanto la herencia cultural como la fe.", "en": "Saint Axayacatl, whose name carries the memory of the ancestors: help me to honor my elders with gratitude and to pass on to my children both cultural heritage and faith." },
    { "day": 6, "es": "San Axayacatl, que el agua de tu nombre evoque siempre el agua del bautismo: intercede para que los bautizados sean fieles a su vocación y vivan como nuevas criaturas en Cristo.", "en": "Saint Axayacatl, may the water of your name always evoke the water of baptism: intercede that the baptized may be faithful to their vocation and live as new creatures in Christ." },
    { "day": 7, "es": "San Axayacatl, ruega por la Iglesia en México y en toda América Latina, para que siga siendo madre fiel de todos los pueblos y culturas que abraza.", "en": "Saint Axayacatl, pray for the Church in Mexico and throughout Latin America, that it may continue to be a faithful mother of all the peoples and cultures it embraces." },
    { "day": 8, "es": "San Axayacatl, protege a todos los que llevan tu nombre: que crezcan en el conocimiento de Dios, en el amor a su familia y en el servicio a su comunidad.", "en": "Saint Axayacatl, protect all who bear your name: may they grow in knowledge of God, in love for their family, and in service to their community." },
    { "day": 9, "es": "San Axayacatl, con gratitud cierro esta novena. Que mi vida sea, como el agua, reflejo del cielo. Lleva mis intenciones ante Dios y ayúdame a vivir con fe, esperanza y amor. Amén.", "en": "Saint Axayacatl, with gratitude I close this novena. May my life be, like water, a reflection of the sky. Carry my intentions before God and help me to live with faith, hope, and love. Amen." }
  ],
  "chaplet": { "available": False, "es": "", "en": "" },
  "litany": {
    "available": True,
    "es": "Señor, ten piedad. Cristo, ten piedad. Señor, ten piedad.\nCristo, óyenos. Cristo, escúchanos.\nDios Padre celestial, ten misericordia de nosotros.\nDios Hijo, Redentor del mundo, ten misericordia de nosotros.\nDios Espíritu Santo, ten misericordia de nosotros.\nSantísima Trinidad, un solo Dios, ten misericordia de nosotros.\nSanta María de Guadalupe, ruega por nosotros.\nSan Axayacatl, reflejo del cielo en la tierra, ruega por nosotros.\nSan Axayacatl, portador del nombre sagrado del agua, ruega por nosotros.\nSan Axayacatl, testigo de la fe inculturada, ruega por nosotros.\nSan Axayacatl, intercesor de los pueblos originarios, ruega por nosotros.\nSan Axayacatl, puente entre la tierra y el cielo, ruega por nosotros.\nSan Axayacatl, patrono de los bautizados con nombres indígenas, ruega por nosotros.\nCordero de Dios, que quitas el pecado del mundo, perdónanos, Señor.\nCordero de Dios, que quitas el pecado del mundo, escúchanos, Señor.\nCordero de Dios, que quitas el pecado del mundo, ten misericordia de nosotros.\nOremos. Dios creador del cielo y de las aguas: por la intercesión de San Axayacatl, concede a todos los pueblos de América que, honrando su herencia, abracen plenamente el Evangelio de tu Hijo y sean reflejos de tu amor en el mundo. Por Cristo nuestro Señor. Amén.",
    "en": "Lord, have mercy. Christ, have mercy. Lord, have mercy.\nChrist, hear us. Christ, graciously hear us.\nGod the Father of Heaven, have mercy on us.\nGod the Son, Redeemer of the world, have mercy on us.\nGod the Holy Spirit, have mercy on us.\nHoly Trinity, one God, have mercy on us.\nHoly Mary of Guadalupe, pray for us.\nSaint Axayacatl, reflection of heaven on earth, pray for us.\nSaint Axayacatl, bearer of the sacred name of water, pray for us.\nSaint Axayacatl, witness of inculturated faith, pray for us.\nSaint Axayacatl, intercessor for indigenous peoples, pray for us.\nSaint Axayacatl, bridge between earth and heaven, pray for us.\nSaint Axayacatl, patron of the baptized with indigenous names, pray for us.\nLamb of God, who takes away the sins of the world, spare us, O Lord.\nLamb of God, who takes away the sins of the world, graciously hear us, O Lord.\nLamb of God, who takes away the sins of the world, have mercy on us.\nLet us pray. God, creator of sky and waters: through the intercession of Saint Axayacatl, grant all the peoples of the Americas that, honoring their heritage, they may fully embrace the Gospel of your Son and be reflections of your love in the world. Through Christ our Lord. Amen."
  },
  "miracles": {
    "available": True,
    "es": "La devoción a San Axayacatl, aunque joven como forma devocional explícita, recoge una larga tradición de espiritualidad indígena cristiana en México y América Central. Numerosos testimonios de personas con este nombre refieren experiencias de profunda paz y sentido de identidad al rezar invocando a San Axayacatl como su patrono bautismal. Varios relatan haber encontrado reconciliación con sus raíces indígenas y su fe cristiana, que en el pasado sentían como contradictorias. También se recogen testimonios de sanaciones de conflictos de identidad cultural, y de jóvenes que, al sentirse acompañados espiritualmente bajo este nombre, encontraron fortaleza para resistir la presión de abandonar la fe de sus padres.",
    "en": "Devotion to Saint Axayacatl, though young as an explicit devotional form, draws on a long tradition of indigenous Christian spirituality in Mexico and Central America. Numerous testimonies from people bearing this name speak of experiences of deep peace and a sense of identity when praying and invoking Saint Axayacatl as their baptismal patron. Several recount having found reconciliation between their indigenous roots and their Christian faith, which they previously felt as contradictory. Testimonies also record healings of cultural identity conflicts, and of young people who, feeling spiritually accompanied under this name, found the strength to resist pressure to abandon the faith of their parents."
  }
}

out = pathlib.Path(r"C:\Users\ggh19\Documents\theuniversalprayer\data\sanaxayacatl.json")
out.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"Written {out} ({out.stat().st_size} bytes)")
