# -*- coding: utf-8 -*-
import json, os

data = {
  "id": "sanblas",
  "name": {
    "es": "San Blas de Sebaste",
    "en": "Saint Blaise of Sebaste"
  },
  "feast_day": {
    "es": "3 de febrero",
    "en": "February 3"
  },
  "image": "/assets/images/sanblas.svg",
  "prayer": {
    "es": "Oh San Blas, obispo y mártir, médico del cuerpo y del alma, hoy acudo a ti con confianza.\n\nTú que sanaste de un huesito de pescado atascado en la garganta al niño que iba a morir, y que desde entonces eres invocado por todos los que sufren males de la garganta y del pecho, escucha mi oración.\n\nIntercede ante Dios por la salud de mi garganta, mis vías respiratorias y mis pulmones (o por los de quien te encomiendo). Que la enfermedad no avance, que el tratamiento sea eficaz, y que pueda respirar y hablar con libertad para glorificar a Dios.\n\nTú que diste tu vida como obispo fiel antes de permitir renunciar a tu fe, dame también a mí la fortaleza de seguir creyendo cuando el dolor o la enfermedad me hacen dudar.\n\nSan Blas, protector de la garganta, de los pulmones y de todos los enfermos del pecho, ruega por nosotros. Amén.",
    "en": "O Saint Blaise, bishop and martyr, healer of body and soul, today I come to you with confidence.\n\nYou who healed the child who was about to die from a fishbone lodged in his throat, and who from that time on have been invoked by all who suffer ailments of the throat and chest, hear my prayer.\n\nIntercede with God for the health of my throat, my airways, and my lungs (or those of the one I entrust to you). May the illness not advance, may the treatment be effective, and may I breathe and speak freely to glorify God.\n\nYou who gave your life as a faithful bishop rather than renounce your faith, give me also the strength to keep believing when pain or illness makes me doubt.\n\nSaint Blaise, protector of the throat, lungs, and all those suffering from chest illness, pray for us. Amen."
  },
  "history": {
    "es": "Blas de Sebaste nació en el siglo III en Armenia, en la ciudad de Sebaste —hoy Sivas, en Turquía. Fue médico antes de ser obispo, y esta doble condición marcaría toda su vida: el cuidado de la carne y el cuidado del alma como dos expresiones de un mismo amor.\n\nFue elegido obispo de Sebaste probablemente a comienzos del siglo IV, durante el último gran período de persecución contra los cristianos bajo el emperador Diocleciano y luego bajo Licinio. Para escapar de la represión, Blas se retiró a una cueva en las montañas del Argeo, donde vivió como ermitaño rodeado de animales salvajes que —según cuenta la tradición— se acercaban mansos a él para ser curados de sus heridas.\n\nFue en ese período cuando ocurrió el milagro más famoso de su vida: unos cazadores al servicio del gobernador romano Agrícola encontraron su cueva y, antes de capturarlo, llevaron a su presencia a un niño que se estaba asfixiando por un huesito de pescado atravesado en la garganta. Blas oró sobre el niño, y el hueso fue expulsado inmediatamente. Desde ese momento, la Iglesia ha invocado su intercesión para los males de la garganta.\n\nTras ser capturado, Blas fue llevado ante el gobernador, que lo presionó para que renunciara al cristianismo. Blas se negó. Fue torturado con peines de hierro para cardar lana —instrumento que se convertiría en uno de sus atributos iconográficos— y finalmente decapitado alrededor del año 316.\n\nSu culto se extendió rápidamente por Oriente y Occidente. En muchas tradiciones católicas, especialmente en España y América Latina, el 3 de febrero se realiza la \"bendición de gargantas\": el sacerdote cruza dos velas bendecidas bajo la barbilla del fiel mientras recita la fórmula: \"Por intercesión de San Blas, obispo y mártir, te libre Dios de los males de garganta y de todo mal.\" Esta costumbre se remonta a la Edad Media y sigue practicándose en innumerables parroquias del mundo.",
    "en": "Blaise of Sebaste was born in the third century in Armenia, in the city of Sebaste — today Sivas, in Turkey. He was a physician before becoming a bishop, and this dual condition would mark his entire life: the care of the flesh and the care of the soul as two expressions of the same love.\n\nHe was chosen bishop of Sebaste probably at the beginning of the fourth century, during the last great period of persecution against Christians under the emperor Diocletian and later under Licinius. To escape the repression, Blaise withdrew to a cave in the mountains of Argaeus, where he lived as a hermit surrounded by wild animals that — according to tradition — came to him meekly to be healed of their wounds.\n\nIt was during that period that the most famous miracle of his life occurred: hunters in the service of the Roman governor Agricolaus found his cave and, before capturing him, brought before him a child who was choking on a fishbone lodged in his throat. Blaise prayed over the child, and the bone was immediately expelled. From that moment, the Church has invoked his intercession for ailments of the throat.\n\nAfter being captured, Blaise was brought before the governor, who pressured him to renounce Christianity. Blaise refused. He was tortured with iron wool combs — an instrument that would become one of his iconographic attributes — and finally beheaded around the year 316.\n\nHis cult spread rapidly through East and West. In many Catholic traditions, especially in Spain and Latin America, on February 3 the 'blessing of throats' takes place: the priest crosses two blessed candles under the chin of the faithful while reciting the formula: 'Through the intercession of Saint Blaise, bishop and martyr, may God deliver you from ailments of the throat and from every evil.' This custom dates to the Middle Ages and continues to be practiced in countless parishes throughout the world."
  },
  "novena_prayers": {
    "es": "Novena a San Blas — Modo de rezar\n\nCada día durante 9 días:\n1. Señal de la Cruz\n2. Padre Nuestro, Ave María, Gloria\n3. Oración propia del día (ver abajo)\n4. Jaculatoria final: «San Blas, obispo y mártir, protege mi garganta y mis vías respiratorias.» (3 veces)\n\nEsta novena puede rezarse por afecciones de garganta, pulmones, asma, tos, voz, o cualquier enfermedad del tracto respiratorio.",
    "en": "Novena to Saint Blaise — How to Pray\n\nEach day for 9 days:\n1. Sign of the Cross\n2. Our Father, Hail Mary, Glory Be\n3. Prayer of the day (see below)\n4. Closing aspiration: 'Saint Blaise, bishop and martyr, protect my throat and airways.' (3 times)\n\nThis novena may be prayed for throat ailments, lung disease, asthma, cough, voice problems, or any illness of the respiratory tract."
  },
  "novena": [
    {
      "day": 1,
      "es": "Día 1 — El médico que se hizo obispo\n\nSan Blas, fuiste médico y pastor. Hoy te pido que intercedas por todos los que sufren enfermedades de la garganta y de los pulmones. Tú que conocías el cuerpo humano y amabas el alma, presenta ante Dios a quien sufre y pide por su sanación.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 1 — The physician who became a bishop\n\nSaint Blaise, you were physician and shepherd. Today I ask you to intercede for all who suffer from ailments of the throat and lungs. You who knew the human body and loved the soul, present before God those who suffer and pray for their healing.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 2,
      "es": "Día 2 — El niño con el hueso en la garganta\n\nSan Blas, tú obraste un milagro por un niño que se ahogaba, y ese milagro resonó a través de los siglos. Hoy te encomiendo a todos los niños que sufren enfermedades de garganta y del aparato respiratorio. Cuídalos como cuidaste a aquel niño que nadie podía salvar.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 2 — The child with the bone in his throat\n\nSaint Blaise, you worked a miracle for a child who was choking, and that miracle echoed through the centuries. Today I entrust to you all children who suffer from throat and respiratory ailments. Care for them as you cared for that child whom no one else could save.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 3,
      "es": "Día 3 — El ermitaño de la montaña\n\nSan Blas, en tu retiro en la cueva, los animales heridos venían a ti y tú los sanabas. Hoy vengo yo también, herido en mi cuerpo (o en el de quien encomiendo), buscando tu intercesión. Acoge mi oración como acogías a los que llegaban a tu cueva.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 3 — The hermit of the mountain\n\nSaint Blaise, in your retreat in the cave, wounded animals came to you and you healed them. Today I also come, wounded in my body (or in the body of the one I entrust to you), seeking your intercession. Receive my prayer as you received those who came to your cave.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 4,
      "es": "Día 4 — La bendición de las gargantas\n\nSan Blas, en tu fiesta los sacerdotes bendicen las gargantas de los fieles con dos velas cruzadas. Hoy recuerdo esa bendición y te pido que renueves en mí su efecto. Que la bendición que recibí sea protección real para mi salud.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 4 — The blessing of throats\n\nSaint Blaise, on your feast day priests bless the throats of the faithful with two crossed candles. Today I recall that blessing and ask you to renew its effect in me. May the blessing I received be real protection for my health.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 5,
      "es": "Día 5 — El regalo de la voz\n\nSan Blas, la garganta es el instrumento de la voz. Con ella rezamos, cantamos, hablamos con quienes amamos, anunciamos el Evangelio. Hoy te pido que protejas mi voz para que pueda seguir usándola en el servicio de Dios y de los demás.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 5 — The gift of the voice\n\nSaint Blaise, the throat is the instrument of the voice. With it we pray, sing, speak with those we love, proclaim the Gospel. Today I ask you to protect my voice so that I may continue to use it in the service of God and others.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 6,
      "es": "Día 6 — El martirio y la fe\n\nSan Blas, cuando te torturaron y te pidieron que negaras a Cristo, dijiste que no. Hoy yo también me comprometo: que la enfermedad no me quite la fe, que el dolor no me aleje de Dios. Ayúdame a sostener mi «sí» a Cristo incluso en la prueba.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 6 — The martyrdom and the faith\n\nSaint Blaise, when you were tortured and asked to deny Christ, you said no. Today I also commit: may illness not rob me of faith, may pain not drive me from God. Help me to hold my 'yes' to Christ even in trial.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 7,
      "es": "Día 7 — Los enfermos crónicos\n\nSan Blas, hoy pienso en quienes conviven con enfermedades respiratorias crónicas: el asma, la EPOC, la fibrosis pulmonar, la apnea del sueño. No buscan un milagro, buscan fuerzas para seguir. Intercede por ellos para que cada día encuentren la energía necesaria y la paz que supera el diagnóstico.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 7 — The chronically ill\n\nSaint Blaise, today I think of those who live with chronic respiratory illnesses: asthma, COPD, pulmonary fibrosis, sleep apnea. They are not looking for a miracle; they are looking for strength to carry on. Intercede for them so that each day they may find the necessary energy and the peace that surpasses the diagnosis.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 8,
      "es": "Día 8 — Por quien está enfermo ahora\n\nSan Blas, hoy te presento a (nombre del enfermo) con toda mi fe. Tú que sanaste de un huesito al niño que iba a morir, sana ahora a esta persona en lo que Dios quiera sanar. Si es la infección, que ceda. Si es el miedo, que se disuelva. Si es el alma, que encuentre paz.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 8 — For the one who is sick now\n\nSaint Blaise, today I present to you (name of the sick person) with all my faith. You who healed with a fishbone the child who was about to die, heal now this person in whatever God wills to heal. If it is the infection, may it yield. If it is the fear, may it dissolve. If it is the soul, may it find peace.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 9,
      "es": "Día 9 — El aliento de vida\n\nSan Blas, respirar es el primer acto de la vida y el último. Hoy en este último día te agradezco el don de cada aliento y te pido que protejas el mío. Que mis pulmones sean templo del Espíritu Santo. Que al final de mis días, mi último aliento sea también una oración.\n\n«San Blas, protector de la garganta, ruega por nosotros.» (3 veces)\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 9 — The breath of life\n\nSaint Blaise, breathing is the first act of life and the last. Today on this final day I thank you for the gift of every breath and ask you to protect mine. May my lungs be a temple of the Holy Spirit. And at the end of my days, may my last breath also be a prayer.\n\n'Saint Blaise, protector of the throat, pray for us.' (3 times)\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    }
  ],
  "chaplet": {
    "available": False,
    "es": "",
    "en": ""
  },
  "litany": {
    "available": True,
    "es": "Letanía a San Blas\n\nSeñor, ten piedad. Cristo, ten piedad. Señor, ten piedad.\nCristo, escúchanos. Cristo, óyenos.\nDios Padre celestial, ten misericordia de nosotros.\nDios Hijo Redentor del mundo, ten misericordia de nosotros.\nDios Espíritu Santo, ten misericordia de nosotros.\nSantísima Trinidad, un solo Dios, ten misericordia de nosotros.\n\nSanta María, Salud de los enfermos, ruega por nosotros.\nSan Blas, obispo fiel y mártir, ruega por nosotros.\nSan Blas, médico del cuerpo y del alma, ruega por nosotros.\nSan Blas, ermitaño de las montañas de Armenia, ruega por nosotros.\nSan Blas, que sanaste al niño del huesito en la garganta, ruega por nosotros.\nSan Blas, que curabas a los animales salvajes, ruega por nosotros.\nSan Blas, protector de las gargantas, ruega por nosotros.\nSan Blas, defensor de los pulmones y las vías respiratorias, ruega por nosotros.\nSan Blas, que no renegaste de Cristo ante el martirio, ruega por nosotros.\nSan Blas, que sufriste la tortura con fortaleza, ruega por nosotros.\nSan Blas, patrono de los cantantes y predicadores, ruega por nosotros.\nSan Blas, amparo de todos los que no pueden respirar, ruega por nosotros.\n\nCordero de Dios, que quitas el pecado del mundo, perdónanos, Señor.\nCordero de Dios, que quitas el pecado del mundo, escúchanos, Señor.\nCordero de Dios, que quitas el pecado del mundo, ten misericordia de nosotros.\n\nV. Ruega por nosotros, San Blas,\nR. Para que seamos dignos de alcanzar las promesas de Jesucristo.\n\nOremos: Oh Dios, que glorificaste a San Blas con el don de los milagros y con la corona del martirio, concédenos por su intercesión la salud de la garganta y de todos los sentidos, y la gracia de perseverar en la fe hasta el fin. Por Jesucristo Nuestro Señor. Amén.",
    "en": "Litany to Saint Blaise\n\nLord, have mercy. Christ, have mercy. Lord, have mercy.\nChrist, hear us. Christ, graciously hear us.\nGod the Father in heaven, have mercy on us.\nGod the Son, Redeemer of the world, have mercy on us.\nGod the Holy Spirit, have mercy on us.\nHoly Trinity, one God, have mercy on us.\n\nHoly Mary, Health of the sick, pray for us.\nSaint Blaise, faithful bishop and martyr, pray for us.\nSaint Blaise, healer of body and soul, pray for us.\nSaint Blaise, hermit of the mountains of Armenia, pray for us.\nSaint Blaise, who healed the child with the bone in his throat, pray for us.\nSaint Blaise, who healed wild animals, pray for us.\nSaint Blaise, protector of throats, pray for us.\nSaint Blaise, defender of lungs and airways, pray for us.\nSaint Blaise, who did not deny Christ before martyrdom, pray for us.\nSaint Blaise, who endured torture with strength, pray for us.\nSaint Blaise, patron of singers and preachers, pray for us.\nSaint Blaise, refuge of all who cannot breathe, pray for us.\n\nLamb of God, who takes away the sins of the world, spare us, O Lord.\nLamb of God, who takes away the sins of the world, graciously hear us, O Lord.\nLamb of God, who takes away the sins of the world, have mercy on us.\n\nV. Pray for us, Saint Blaise,\nR. That we may be made worthy of the promises of Christ.\n\nLet us pray: O God, who glorified Saint Blaise with the gift of miracles and with the crown of martyrdom, grant us through his intercession health of throat and all the senses, and the grace to persevere in faith to the end. Through Christ our Lord. Amen."
  },
  "miracles": {
    "available": True,
    "es": "1. EL NIÑO SALVADO DE LA MUERTE POR UN HUESO EN LA GARGANTA\nEl milagro más célebre de San Blas ocurrió mientras estaba preso, camino a su ejecución. Una madre desesperada se arrojó a sus pies con su hijo pequeño que se estaba asfixiando por un hueso de pescado atascado en la garganta. Los médicos no habían podido extraerlo. Blas tomó al niño entre sus manos, oró sobre él, y el hueso fue expulsado de inmediato. El niño sobrevivió. Este milagro es el origen de la tradición de la bendición de gargantas que se practica en todo el mundo católico el 3 de febrero, día de su fiesta.\n\n2. LA MUJER DE LA CERDA Y EL LOBO\nSegún otra tradición recogida en el Martirologio Romano y en diversas fuentes medievales, una pobre viuda fue al monte a buscar a su único cerdo y lo encontró en las garras de un lobo. Desesperada, fue a ver al obispo Blas y le suplicó que intercediera. Blas le prometió que el animal le sería devuelto. Al poco tiempo, el lobo soltó la cerda y huyó. La mujer, en agradecimiento, sacrificó el cerdo y llevó su cabeza y sus patas a Blas en la cárcel. Blas la bendijo y le dijo que esos alimentos serían siempre abundantes en su casa. Desde entonces la viuda nunca pasó necesidad.\n\n3. EL MARTIRIO COMO TESTIMONIO\nLos verdugos intentaron desgarrar la carne de Blas con peines de hierro para cardar lana, pero Blas no renegó de Cristo ni bajo tortura. Finalmente fue decapitado. La fortaleza de su fe durante el martirio fue considerada por la Iglesia primitiva como un milagro moral: la gracia de Dios que sostiene al hombre más allá de los límites humanos. Su ejemplo convirtió a muchos paganos que presenciaron su muerte.",
    "en": "1. THE CHILD SAVED FROM DEATH BY A BONE IN THE THROAT\nThe most celebrated miracle of Saint Blaise occurred while he was imprisoned, on his way to execution. A desperate mother threw herself at his feet with her small child who was choking on a fishbone lodged in his throat. Doctors had been unable to remove it. Blaise took the child in his hands, prayed over him, and the bone was immediately expelled. The child survived. This miracle is the origin of the tradition of the blessing of throats practiced throughout the Catholic world on February 3, his feast day.\n\n2. THE WOMAN WITH THE SOW AND THE WOLF\nAccording to another tradition recorded in the Roman Martyrology and various medieval sources, a poor widow went to the mountain to look for her only pig and found it in the claws of a wolf. Desperate, she went to see Bishop Blaise and begged him to intercede. Blaise promised her that the animal would be returned. Shortly afterward, the wolf released the pig and fled. The woman, in gratitude, slaughtered the pig and brought its head and feet to Blaise in prison. Blaise blessed them and told her that such food would always be abundant in her house. From that time on, the widow never went without.\n\n3. THE MARTYRDOM AS TESTIMONY\nThe executioners attempted to tear Blaise's flesh with iron wool combs, but Blaise did not renounce Christ even under torture. He was finally beheaded. The strength of his faith during the martyrdom was considered by the early Church a moral miracle: the grace of God sustaining man beyond human limits. His example converted many pagans who witnessed his death."
  }
}

out_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'sanblas.json')
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print('sanblas.json creado OK')
