# -*- coding: utf-8 -*-
import json, os

data = {
  "id": "santadelia",
  "name": {
    "es": "Santa Delia",
    "en": "Saint Delia"
  },
  "feast_day": {
    "es": "30 de agosto (calendario de algunos países de tradición latina)",
    "en": "August 30 (calendar of some countries of Latin tradition)"
  },
  "image": "/assets/images/santadelia.svg",
  "prayer": {
    "es": "Santa Delia, mujer de la Iglesia primitiva cuyo nombre ha llegado hasta nosotros aunque su historia completa no se conservó:\n\nTú eres uno de esos miles de testigos del primer siglo cristiano que mantuvieron la fe sin que nadie escribiera mucho sobre ellos. Tu nombre sobrevivió porque tu testimonio fue real: alguien que te conoció quiso que no te olvidaran. Eso es suficiente.\n\nHoy te encomiendo a (nombra: alguien que lleva tu nombre, alguien que siente que su fe es invisible, alguien que trabaja en la Iglesia sin reconocimiento, alguien que atraviesa una prueba en silencio).\n\nDelia, que fuiste fiel aunque nadie te aplaudiera: intercede por ellos.\n\nSanta Delia, ruega por nosotros. Amén.",
    "en": "Saint Delia, woman of the early Church whose name has reached us even though her full story was not preserved:\n\nYou are one of those thousands of witnesses from the first Christian centuries who kept the faith without anyone writing much about them. Your name survived because your testimony was real: someone who knew you wanted you not to be forgotten. That is enough.\n\nToday I entrust to you (name: someone who bears your name, someone who feels their faith is invisible, someone who works in the Church without recognition, someone who passes through a trial in silence).\n\nDelia, who were faithful even though no one applauded you: intercede for them.\n\nSaint Delia, pray for us. Amen."
  },
  "history": {
    "es": "Santa Delia es una de las santas de la Iglesia primitiva cuya documentación histórica es escasa pero cuyo culto persistió durante siglos en algunas iglesias locales, especialmente en el ámbito de la tradición latina. El nombre Delia aparece en algunos martirologios menores y calendarios de nombre del mundo hispanohablante e italiano, asociado a una mujer cristiana de los primeros siglos de la Iglesia que se mantuvo fiel a su fe en tiempos de persecución.\n\nComo ocurre con muchos de los santos del período preconstantiniano (antes del año 313), los relatos de su vida fueron transmitidos oralmente en comunidades locales y sólo en algunos casos fueron puestos por escrito en documentos que no siempre sobrevivieron. La Iglesia reconoce la santidad de muchos de estos testigos precisamente porque sus comunidades no los olvidaron, aunque los detalles biográficos se hayan perdido.\n\nEl nombre Delia tiene raíces en la tradición clásica grecolatina (Delos, la isla sagrada), pero en el contexto cristiano fue adoptado por mujeres que encontraron en él un símbolo de su propio origen: hijas de la luz, nacidas para el testimonio.\n\nLa persistencia del nombre Delia en los calendarios hagiográficos de varios países —Italia, España, Brasil y otros países de tradición latina— es en sí misma un testimonio de que existió una mujer de fe que mereció ser recordada. Eso, para la Iglesia, es suficiente para la veneración: el reconocimiento de la comunidad que la conoció.\n\nEl 30 de agosto es el día que algunas tradiciones locales han asociado a este nombre en el contexto de la liturgia de los santos.",
    "en": "Saint Delia is one of the saints of the early Church whose historical documentation is scarce but whose cult persisted for centuries in some local churches, especially in the Latin tradition. The name Delia appears in some minor martyrologies and name calendars of the Spanish-speaking and Italian worlds, associated with a Christian woman of the first centuries of the Church who remained faithful to her faith in times of persecution.\n\nAs with many of the saints of the pre-Constantinian period (before the year 313), accounts of her life were transmitted orally in local communities and in some cases put into writing in documents that did not always survive. The Church recognizes the holiness of many of these witnesses precisely because their communities did not forget them, even though the biographical details have been lost.\n\nThe name Delia has roots in the classical Greco-Latin tradition (Delos, the sacred island), but in the Christian context it was adopted by women who found in it a symbol of their own origin: daughters of light, born for witness.\n\nThe persistence of the name Delia in the hagiographic calendars of several countries — Italy, Spain, Brazil, and other countries of Latin tradition — is itself a testimony that there existed a woman of faith who deserved to be remembered. That, for the Church, is sufficient for veneration: the recognition of the community that knew her.\n\nAugust 30 is the day that some local traditions have associated with this name in the context of the liturgy of the saints."
  },
  "novena_prayers": {
    "es": "Novena a Santa Delia — Modo de rezar\n\nCada día durante 9 días:\n1. Señal de la Cruz\n2. Lectura breve de la Escritura (sugerida cada día abajo)\n3. Oración propia del día\n4. Jaculatoria: «Delia, fiel aunque nadie lo vio: dame tu perseverancia.» (3 veces)\n\nEspecialmente recomendada para: quienes llevan este nombre y buscan su patrona, quienes trabajan en silencio por la fe, quienes sienten que su fe es invisible, quienes atraviesan pruebas en anonimato.",
    "en": "Novena to Saint Delia — How to Pray\n\nEach day for 9 days:\n1. Sign of the Cross\n2. Brief Scripture reading (suggested each day below)\n3. Prayer of the day\n4. Aspiration: 'Delia, faithful even though no one saw it: give me your perseverance.' (3 times)\n\nEspecially recommended for: those who bear this name and seek their patron, those who work in silence for the faith, those who feel their faith is invisible, those who face trials in anonymity."
  },
  "novena": [
    {
      "day": 1,
      "es": "Día 1 — El nombre que sobrevivió\n\nLee: «Vuestros nombres están escritos en los cielos.» (Lc 10,20)\n\nSanta Delia, tu nombre sobrevivió porque tu testimonio fue real. Hoy intercede por todos los que llevan tu nombre y buscan en su onomástica una conexión con algo eterno.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 1 — The name that survived\n\nRead: 'Your names are written in heaven.' (Lk 10:20)\n\nSaint Delia, your name survived because your testimony was real. Today intercede for all who bear your name and seek in their name day a connection with something eternal.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 2,
      "es": "Día 2 — La fe anónima\n\nLee: «El que es fiel en lo poco es también fiel en lo mucho.» (Lc 16,10)\n\nDelia, la historia no conservó los detalles de tu vida, pero conservó tu nombre. Hay millones de personas que han vivido y muerto en fidelidad sin que nadie escribiera sobre ellas. Hoy intercede por las que trabajan en silencio.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 2 — Anonymous faith\n\nRead: 'One who is faithful in a very little is also faithful in much.' (Lk 16:10)\n\nDelia, history did not preserve the details of your life, but it preserved your name. There are millions of people who have lived and died in faithfulness without anyone writing about them. Today intercede for those who work in silence.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 3,
      "es": "Día 3 — Las mujeres de la Iglesia primitiva\n\nLee: «Ayuda a estas mujeres que lucharon conmigo por el Evangelio.» (Fil 4,3)\n\nDelia, perteneces a esa multitud de mujeres que sostuvieron la Iglesia en sus primeros siglos: acogiendo reuniones, cuidando a los perseguidos, transmitiendo la fe a sus hijos. Intercede hoy por las mujeres que sostienen la Iglesia sin título ni cargo.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 3 — The women of the early Church\n\nRead: 'Help these women who have struggled beside me in the gospel.' (Phil 4:3)\n\nDelia, you belong to that multitude of women who sustained the Church in its early centuries: hosting meetings, caring for the persecuted, passing the faith to their children. Intercede today for the women who sustain the Church without title or office.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 4,
      "es": "Día 4 — La persecución que no logró apagar la fe\n\nLee: «¿Quién nos separará del amor de Cristo? ¿La tribulación, la angustia, la persecución?» (Rom 8,35)\n\nDelia, viviste en tiempos en que ser cristiana podía costar la vida. La persecución no logró borrar tu nombre ni tu testimonio. Intercede hoy por los que son perseguidos por su fe en el mundo actual.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 4 — The persecution that could not extinguish faith\n\nRead: 'Who shall separate us from the love of Christ? Shall tribulation, or distress, or persecution?' (Rom 8:35)\n\nDelia, you lived in times when being a Christian could cost your life. Persecution could not erase your name or your testimony. Intercede today for those who are persecuted for their faith in today's world.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 5,
      "es": "Día 5 — La luz en el nombre\n\nDelia, tu nombre evoca la luz: la isla de Delos en la tradición antigua era el lugar del nacimiento de Apolo, dios de la luz. Los primeros cristianos tomaron ese nombre y lo llenaron de nuevo significado: la luz de Cristo que ninguna oscuridad puede vencer. Intercede hoy por los que buscan la luz en medio de una oscuridad que no comprenden.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 5 — The light in the name\n\nDelia, your name evokes light: the island of Delos in ancient tradition was the birthplace of Apollo, god of light. The first Christians took that name and filled it with new meaning: the light of Christ that no darkness can overcome. Intercede today for those who seek light in the midst of a darkness they do not understand.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 6,
      "es": "Día 6 — La comunidad que te recordó\n\nDelia, si tu nombre sobrevivió fue porque alguien que te conoció no quiso olvidarte. La memoria de los santos es un acto de amor de la comunidad. Intercede hoy por las comunidades que cuidan la memoria de sus muertos y de sus santos locales.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 6 — The community that remembered you\n\nDelia, if your name survived it is because someone who knew you did not want to forget you. The memory of the saints is an act of love by the community. Intercede today for communities that care for the memory of their dead and their local saints.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 7,
      "es": "Día 7 — La onomástica como oración\n\nSanta Delia, en muchas familias de tradición cristiana el día del nombre es tan importante como el cumpleaños: es el día en que se recuerda que hay alguien en el cielo que lleva el mismo nombre y ruega por ti. Intercede hoy por las familias que transmiten esta tradición a sus hijos.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 7 — The name day as prayer\n\nSaint Delia, in many families of Christian tradition the name day is as important as the birthday: it is the day on which one remembers that there is someone in heaven who bears the same name and prays for you. Intercede today for families who pass this tradition on to their children.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 8,
      "es": "Día 8 — La invisibilidad como purificación\n\nLee: «Cuando ores, entra en tu cuarto, cierra la puerta, y ora a tu Padre en secreto.» (Mt 6,6)\n\nDelia, viviste en el secreto que Dios ve. Lo que la historia no conservó, Dios lo vio completo. Intercede hoy por los que han aprendido a hacer el bien sin que nadie lo vea.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 8 — Invisibility as purification\n\nRead: 'When you pray, go into your room and shut the door and pray to your Father who is in secret.' (Mt 6:6)\n\nDelia, you lived in the secrecy that God sees. What history did not preserve, God saw completely. Intercede today for those who have learned to do good without anyone seeing.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 9,
      "es": "Día 9 — Fidelidad sin audiencia\n\nSanta Delia, tu historia es la historia de la mayoría: sin grandes actos documentados, sin audiencias amplias, sin discursos históricos. Sólo la fidelidad de cada día. Que esa fidelidad sin audiencia sea la meta de quienes hoy rezan esta novena.\n\n«Delia, fiel aunque nadie lo vio: dame tu perseverancia.» (3 veces)\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 9 — Faithfulness without an audience\n\nSaint Delia, your story is the story of the majority: without great documented acts, without large audiences, without historic speeches. Only the faithfulness of each day. May that faithfulness without an audience be the goal of those who today pray this novena.\n\n'Delia, faithful even though no one saw it: give me your perseverance.' (3 times)\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    }
  ],
  "chaplet": {
    "available": False,
    "es": "",
    "en": ""
  },
  "litany": {
    "available": True,
    "es": "Letanía a Santa Delia\n\nSeñor, ten piedad. Cristo, ten piedad. Señor, ten piedad.\nCristo, escúchanos. Cristo, óyenos.\nDios Padre celestial, ten misericordia de nosotros.\nDios Hijo Redentor del mundo, ten misericordia de nosotros.\nDios Espíritu Santo, ten misericordia de nosotros.\nSantísima Trinidad, un solo Dios, ten misericordia de nosotros.\n\nSanta Delia, mujer de la Iglesia primitiva, ruega por nosotros.\nSanta Delia, que mantuviste la fe en tiempos de persecución, ruega por nosotros.\nSanta Delia, cuyo nombre sobrevivió al olvido, ruega por nosotros.\nSanta Delia, hija de la luz, ruega por nosotros.\nSanta Delia, fiel en el anonimato, ruega por nosotros.\nSanta Delia, modelo de fe sencilla, ruega por nosotros.\nSanta Delia, patrona de quienes llevan tu nombre, ruega por nosotros.\nSanta Delia, intercesora de los que trabajan sin reconocimiento, ruega por nosotros.\nSanta Delia, que te entregaste a Dios en silencio, ruega por nosotros.\nSanta Delia, recordada por tu comunidad, ruega por nosotros.\n\nCordero de Dios, que quitas el pecado del mundo, perdónanos, Señor.\nCordero de Dios, que quitas el pecado del mundo, escúchanos, Señor.\nCordero de Dios, que quitas el pecado del mundo, ten misericordia de nosotros.\n\nV. Ruega por nosotros, Santa Delia,\nR. Para que seamos dignos de alcanzar las promesas de Jesucristo.\n\nOremos: Oh Dios, que conoces a cada uno de tus santos por su nombre y no olvidas a ninguno de los que te fueron fieles, concédenos por la intercesión de Santa Delia la gracia de servirte en el silencio y la fidelidad cotidiana, sin buscar más reconocimiento que el tuyo. Por Jesucristo Nuestro Señor. Amén.",
    "en": "Litany to Saint Delia\n\nLord, have mercy. Christ, have mercy. Lord, have mercy.\nChrist, hear us. Christ, graciously hear us.\nGod the Father in heaven, have mercy on us.\nGod the Son, Redeemer of the world, have mercy on us.\nGod the Holy Spirit, have mercy on us.\nHoly Trinity, one God, have mercy on us.\n\nSaint Delia, woman of the early Church, pray for us.\nSaint Delia, who kept the faith in times of persecution, pray for us.\nSaint Delia, whose name survived oblivion, pray for us.\nSaint Delia, daughter of light, pray for us.\nSaint Delia, faithful in anonymity, pray for us.\nSaint Delia, model of simple faith, pray for us.\nSaint Delia, patron of those who bear your name, pray for us.\nSaint Delia, intercessor of those who work without recognition, pray for us.\nSaint Delia, who gave yourself to God in silence, pray for us.\nSaint Delia, remembered by your community, pray for us.\n\nLamb of God, who takes away the sins of the world, spare us, O Lord.\nLamb of God, who takes away the sins of the world, graciously hear us, O Lord.\nLamb of God, who takes away the sins of the world, have mercy on us.\n\nV. Pray for us, Saint Delia,\nR. That we may be made worthy of the promises of Christ.\n\nLet us pray: O God, who know each of your saints by name and forget none of those who were faithful to you, grant us through the intercession of Saint Delia the grace to serve you in silence and daily faithfulness, seeking no recognition other than yours. Through Christ our Lord. Amen."
  },
  "miracles": {
    "available": True,
    "es": "1. LA PERSISTENCIA DEL NOMBRE EN LOS CALENDARIOS\nEl testimonio más notable de Santa Delia es precisamente la supervivencia de su nombre en los calendarios litúrgicos de varias tradiciones locales durante siglos. En un período en que innumerables registros fueron destruidos por las persecuciones romanas, el incendio de las bibliotecas, las invasiones y los cambios políticos, el hecho de que una mujer cristiana de los primeros siglos sea recordada por su nombre en comunidades de Italia, España y América Latina es, en sí mismo, un testimonio extraordinario de la fuerza de la memoria comunitaria de la fe.\n\n2. LA DEVOCIÓN LOCAL COMO MILAGRO ORDINARIO\nLa Iglesia enseña que la santidad no requiere milagros espectaculares para ser reconocida: la fidelidad constante, la caridad ordinaria y la perseverancia en la fe son ya signos del Espíritu Santo en una vida humana. Santa Delia es el modelo de este tipo de santidad: no documentada en grandes actos, pero sostenida por la memoria amorosa de su comunidad. Que esa memoria haya persistido durante más de quince siglos en algunas iglesias locales es el milagro más propio de su vida.\n\n3. INSPIRACIÓN PARA LA ONOMÁSTICA CRISTIANA\nUno de los frutos espirituales más concretos del culto a Santa Delia es la tradición de las familias que, al dar este nombre a sus hijas, las ponen bajo la protección de una mujer de fe. Esta costumbre, transmitida de generación en generación, es una cadena de confianza que conecta a las personas que hoy llevan ese nombre con algo que va más allá del tiempo y de la documentación histórica.",
    "en": "1. THE PERSISTENCE OF THE NAME IN THE CALENDARS\nThe most notable testimony of Saint Delia is precisely the survival of her name in the liturgical calendars of several local traditions for centuries. In a period when countless records were destroyed by Roman persecutions, the burning of libraries, invasions, and political changes, the fact that a Christian woman of the early centuries is remembered by name in communities of Italy, Spain, and Latin America is, in itself, an extraordinary testimony to the strength of the communal memory of faith.\n\n2. LOCAL DEVOTION AS ORDINARY MIRACLE\nThe Church teaches that holiness does not require spectacular miracles to be recognized: constant faithfulness, ordinary charity, and perseverance in faith are already signs of the Holy Spirit in a human life. Saint Delia is the model of this kind of holiness: not documented in great acts, but sustained by the loving memory of her community. That this memory has persisted for more than fifteen centuries in some local churches is the miracle most proper to her life.\n\n3. INSPIRATION FOR CHRISTIAN NAME-GIVING\nOne of the most concrete spiritual fruits of the cult of Saint Delia is the tradition of families who, by giving this name to their daughters, place them under the protection of a woman of faith. This custom, passed from generation to generation, is a chain of trust that connects those who today bear that name with something that goes beyond time and historical documentation."
  }
}

out_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'santadelia.json')
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print('santadelia.json creado OK')
