# -*- coding: utf-8 -*-
import json, os

data = {
  "id": "sanjorge",
  "name": {
    "es": "San Jorge",
    "en": "Saint George"
  },
  "feast_day": {
    "es": "23 de abril",
    "en": "April 23"
  },
  "image": "/assets/images/sanjorge.svg",
  "prayer": {
    "es": "San Jorge, mártir y soldado de Cristo, que preferiste la lealtad a Dios sobre la obediencia a un edicto injusto, y que pagaste esa fidelidad con tu propia vida:\n\nHoy vengo a pedirte que intercedas por (nombra tu intención: alguien que sirve en las fuerzas armadas, alguien que enfrenta una injusticia que parece invencible, alguien que necesita valentía para defender lo que es correcto, alguien que está en peligro físico o moral).\n\nJorge, que venciste al dragón que es símbolo de todo mal, de todo miedo, de toda opresión: ruega por nosotros para que no cedamos ante el poder del mal, sino que permanezcamos firmes en la fe.\n\nEn la tradición de la caballería cristiana, tu nombre fue invocado en las batallas más difíciles. Hoy nuestra batalla es diferente, pero no menos real: es la batalla por la integridad, por la verdad, por la protección de los inocentes.\n\nSan Jorge, mártir valeroso: ruega por nosotros. Amén.",
    "en": "Saint George, martyr and soldier of Christ, who preferred loyalty to God over obedience to an unjust edict, and who paid that faithfulness with your own life:\n\nToday I come to ask you to intercede for (name your intention: someone who serves in the armed forces, someone who faces an injustice that seems invincible, someone who needs courage to defend what is right, someone who is in physical or moral danger).\n\nGeorge, who conquered the dragon that is the symbol of all evil, all fear, all oppression: pray for us that we may not yield to the power of evil but remain firm in faith.\n\nIn the tradition of Christian chivalry, your name was invoked in the most difficult battles. Today our battle is different, but no less real: it is the battle for integrity, for truth, for the protection of the innocent.\n\nSaint George, courageous martyr: pray for us. Amen."
  },
  "history": {
    "es": "San Jorge fue un soldado romano de origen capadocio (región de la actual Turquía) que vivió probablemente en la segunda mitad del siglo III y fue martirizado durante las persecuciones del emperador Diocleciano, hacia el año 303, en la ciudad de Lida (en la actual Israel). Es uno de los mártires más venerados de la cristiandad, con un culto que se extiende desde la Iglesia de Oriente hasta las tradiciones de Europa Occidental.\n\nSegún los relatos que la tradición ha transmitido, Jorge era oficial del ejército romano y cristiano practicante. Cuando el edicto de Diocleciano ordenó a los soldados renegar de su fe y participar en los sacrificios paganos, Jorge se negó públicamente. Fue arrestado, sometido a torturas y finalmente decapitado el 23 de abril. Su valentía ante la ejecución convirtió su figura en el arquetipo del mártir soldado: alguien que conocía el valor de la vida pero no lo puso por encima del valor de la verdad.\n\nLa historia del dragón, tan vinculada a su iconografía, es una leyenda medieval que no pretende ser historia literal, sino teológica: el dragón representa la persecución del mal, la injusticia y la opresión. Jorge a caballo, con su lanza, venciendo al dragón, es la imagen de Cristo venciendo al pecado y a la muerte, y del cristiano llamado a combatir el mal no con violencia sin sentido sino con la fuerza de la fe y la justicia.\n\nSan Jorge es patrono de England (Inglaterra), Cataluña, Georgia, Portugal, Lituania, numerosas ciudades, y de los soldados, los scouts, los jinetes y los caballeros. Su fiesta el 23 de abril es día nacional en Inglaterra y festivo en varias regiones del mundo hispano.\n\nFue canonizado en el santoral de la Iglesia desde los primeros siglos, y el Concilio de Oxford (1222) declaró el 23 de abril día de precepto en Inglaterra. Su imagen ha sido llevada en banderas, escudos y estandartes durante más de mil años.",
    "en": "Saint George was a Roman soldier of Cappadocian origin (a region of modern-day Turkey) who lived probably in the second half of the third century and was martyred during the persecutions of Emperor Diocletian, around the year 303, in the city of Lydda (in present-day Israel). He is one of the most venerated martyrs in Christianity, with a cult extending from the Eastern Church to the traditions of Western Europe.\n\nAccording to the accounts that tradition has passed down, George was an officer in the Roman army and a practicing Christian. When Diocletian's edict ordered soldiers to renounce their faith and participate in pagan sacrifices, George refused publicly. He was arrested, subjected to torture, and finally beheaded on April 23. His courage in the face of execution made his figure the archetype of the soldier-martyr: someone who knew the value of life but did not place it above the value of truth.\n\nThe story of the dragon, so linked to his iconography, is a medieval legend that does not aim to be literal history, but theological: the dragon represents the persecution of evil, injustice, and oppression. George on horseback, with his lance, conquering the dragon, is the image of Christ conquering sin and death, and of the Christian called to fight evil not with senseless violence but with the strength of faith and justice.\n\nSaint George is patron of England, Catalonia, Georgia, Portugal, Lithuania, numerous cities, and of soldiers, scouts, riders, and knights. His feast on April 23 is a national day in England and a holiday in several regions of the Hispanic world.\n\nHe was canonized in the Church's calendar from the earliest centuries, and the Council of Oxford (1222) declared April 23 a day of obligation in England. His image has been carried on flags, shields, and banners for more than a thousand years."
  },
  "novena_prayers": {
    "es": "Novena a San Jorge — Modo de rezar\n\nCada día durante 9 días:\n1. Señal de la Cruz\n2. Lectura breve de la Escritura (sugerida cada día abajo)\n3. Oración propia del día\n4. Jaculatoria: «San Jorge, valeroso mártir: dame tu fortaleza.» (3 veces)\n\nEspecialmente recomendada para: militares y policías, personas que enfrentan injusticias, quienes necesitan valentía moral, los que están en situaciones de peligro.",
    "en": "Novena to Saint George — How to Pray\n\nEach day for 9 days:\n1. Sign of the Cross\n2. Brief Scripture reading (suggested each day below)\n3. Prayer of the day\n4. Aspiration: 'Saint George, courageous martyr: give me your strength.' (3 times)\n\nEspecially recommended for: military and police personnel, people facing injustice, those who need moral courage, those in dangerous situations."
  },
  "novena": [
    {
      "day": 1,
      "es": "Día 1 — El soldado que eligió a Dios\n\nLee: «Vestíos de toda la armadura de Dios para que podáis resistir las acechanzas del diablo.» (Ef 6,11)\n\nSan Jorge, fuiste soldado del emperador pero ante todo soldado de Cristo. Cuando tuviste que elegir entre los dos, elegiste sin vacilar. Intercede hoy por todos los que sirven en las fuerzas armadas y piden la gracia de mantener su integridad moral.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 1 — The soldier who chose God\n\nRead: 'Put on the whole armor of God, that you may be able to stand against the schemes of the devil.' (Eph 6:11)\n\nSaint George, you were a soldier of the emperor but above all a soldier of Christ. When you had to choose between the two, you chose without hesitation. Intercede today for all who serve in the armed forces and ask for the grace to maintain their moral integrity.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 2,
      "es": "Día 2 — El martirio como victoria\n\nLee: «Sé fiel hasta la muerte y te daré la corona de la vida.» (Ap 2,10)\n\nJorge, la tortura no te doblegó y la amenaza de muerte no te hizo renegar. Lo que los emperadores llamaron derrota, la Iglesia lo llamó victoria. Intercede hoy por quienes sufren persecución por su fe en cualquier lugar del mundo.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 2 — Martyrdom as victory\n\nRead: 'Be faithful unto death, and I will give you the crown of life.' (Rev 2:10)\n\nGeorge, torture did not break you and the threat of death did not make you renounce. What the emperors called defeat, the Church called victory. Intercede today for those who suffer persecution for their faith anywhere in the world.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 3,
      "es": "Día 3 — El dragón: el símbolo del mal\n\nLee: «Sed sobrios y velad. Vuestro adversario el diablo ronda como león rugiente buscando a quien devorar.» (1 Pe 5,8)\n\nJorge, el dragón que la tradición puso a tus pies es el símbolo de todo lo que destruye: el miedo, la injusticia, el poder abusivo, el mal moral. Intercede hoy por todos los que enfrentan situaciones que parecen invencibles.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 3 — The dragon: the symbol of evil\n\nRead: 'Be sober-minded; be watchful. Your adversary the devil prowls around like a roaring lion, seeking someone to devour.' (1 Pt 5:8)\n\nGeorge, the dragon that tradition placed at your feet is the symbol of everything that destroys: fear, injustice, abusive power, moral evil. Intercede today for all who face situations that seem invincible.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 4,
      "es": "Día 4 — La valentía moral\n\nLee: «No os he dado espíritu de cobardía, sino de poder, de amor y de sensatez.» (2 Tim 1,7)\n\nJorge, la valentía que mostraste no fue arrogancia sino claridad: sabías lo que era verdad y lo defendiste. Intercede hoy por quienes necesitan valentía para decir la verdad en su trabajo, su familia o su comunidad.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 4 — Moral courage\n\nRead: 'For God gave us a spirit not of fear but of power and love and self-control.' (2 Tim 1:7)\n\nGeorge, the courage you showed was not arrogance but clarity: you knew what was true and you defended it. Intercede today for those who need courage to speak the truth at work, in their family, or in their community.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 5,
      "es": "Día 5 — La protección de los inocentes\n\nEn la leyenda, Jorge interviene para liberar a una doncella que iba a ser devorada por el dragón. Ese gesto de protección al inocente es el núcleo de la espiritualidad del caballero cristiano. Intercede hoy por los que trabajan para proteger a los vulnerables: policías, trabajadores sociales, defensores de los derechos humanos.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 5 — The protection of the innocent\n\nIn the legend, George intervenes to free a maiden who was about to be devoured by the dragon. That gesture of protection for the innocent is the core of the spirituality of the Christian knight. Intercede today for those who work to protect the vulnerable: police officers, social workers, human rights defenders.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 6,
      "es": "Día 6 — Los que sirven a dos lealtades\n\nJorge vivió la tensión de ser a la vez ciudadano del Imperio y ciudadano del Reino de Dios. Esa tensión es real para muchos creyentes que trabajan en estructuras donde a veces se les pide lo que no deberían dar. Intercede hoy por todos los que viven esa tensión con integridad.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 6 — Those who serve two loyalties\n\nGeorge lived the tension of being both a citizen of the Empire and a citizen of the Kingdom of God. That tension is real for many believers who work in structures where they are sometimes asked for what they should not give. Intercede today for all who live that tension with integrity.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 7,
      "es": "Día 7 — Patrono de naciones y ciudades\n\nSan Jorge, tu imagen flota en la bandera de Inglaterra, en el escudo de Cataluña, en los estandartes de Georgia. Fuiste adoptado por pueblos enteros como símbolo de algo que querían ser: valientes, rectos, defensores de la verdad. Intercede hoy por los que gobiernan naciones y ciudades para que sean dignos del ideal que representas.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 7 — Patron of nations and cities\n\nSaint George, your image flies on the flag of England, on the coat of arms of Catalonia, on the banners of Georgia. Whole peoples adopted you as a symbol of what they wanted to be: brave, upright, defenders of truth. Intercede today for those who govern nations and cities, that they may be worthy of the ideal you represent.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 8,
      "es": "Día 8 — El martirio en Lida\n\nLee: «Si el grano de trigo que cae en la tierra no muere, queda solo; pero si muere, da mucho fruto.» (Jn 12,24)\n\nJorge, fuiste ejecutado en Lida, una ciudad que hoy lleva el nombre de Lod en Israel. Tu sangre fecundó una de las iglesias más antiguas de Tierra Santa que lleva tu nombre hasta hoy. Intercede por todos los que dan su vida por algo que vale más que la vida.\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 8 — The martyrdom at Lydda\n\nRead: 'Truly, truly, I say to you, unless a grain of wheat falls into the earth and dies, it remains alone; but if it dies, it bears much fruit.' (Jn 12:24)\n\nGeorge, you were executed in Lydda, a city that today bears the name of Lod in Israel. Your blood nourished one of the oldest churches in the Holy Land that bears your name to this day. Intercede for all who give their lives for something worth more than life.\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    },
    {
      "day": 9,
      "es": "Día 9 — La cruz roja sobre fondo blanco\n\nSan Jorge, la cruz que llevas en el pecho y que los cruzados pintaron en sus túnicas es la cruz de Cristo: roja sobre blanco, la sangre del martirio sobre la pureza de la fe. Que esa misma cruz sea mi guía en las batallas que hoy me tocan vivir.\n\n«San Jorge, valeroso mártir: dame tu fortaleza.» (3 veces)\n\nReza: 1 Padre Nuestro, 1 Ave María, 1 Gloria.",
      "en": "Day 9 — The red cross on white ground\n\nSaint George, the cross you bear on your chest and which the Crusaders painted on their tunics is the cross of Christ: red on white, the blood of martyrdom on the purity of faith. May that same cross be my guide in the battles I face today.\n\n'Saint George, courageous martyr: give me your strength.' (3 times)\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be."
    }
  ],
  "chaplet": {
    "available": False,
    "es": "",
    "en": ""
  },
  "litany": {
    "available": True,
    "es": "Letanía a San Jorge\n\nSeñor, ten piedad. Cristo, ten piedad. Señor, ten piedad.\nCristo, escúchanos. Cristo, óyenos.\nDios Padre celestial, ten misericordia de nosotros.\nDios Hijo Redentor del mundo, ten misericordia de nosotros.\nDios Espíritu Santo, ten misericordia de nosotros.\nSantísima Trinidad, un solo Dios, ten misericordia de nosotros.\n\nSan Jorge, mártir de Cristo, ruega por nosotros.\nSan Jorge, soldado valeroso, ruega por nosotros.\nSan Jorge, que preferiste la muerte a la traición, ruega por nosotros.\nSan Jorge, vencedor del dragón, ruega por nosotros.\nSan Jorge, protector de los inocentes, ruega por nosotros.\nSan Jorge, patrono de Inglaterra y Cataluña, ruega por nosotros.\nSan Jorge, modelo de la caballería cristiana, ruega por nosotros.\nSan Jorge, defensor de la justicia, ruega por nosotros.\nSan Jorge, escudo de los perseguidos, ruega por nosotros.\nSan Jorge, testigo de la fe hasta la muerte, ruega por nosotros.\nSan Jorge, patrono de los soldados y scouts, ruega por nosotros.\n\nCordero de Dios, que quitas el pecado del mundo, perdónanos, Señor.\nCordero de Dios, que quitas el pecado del mundo, escúchanos, Señor.\nCordero de Dios, que quitas el pecado del mundo, ten misericordia de nosotros.\n\nV. Ruega por nosotros, San Jorge,\nR. Para que seamos dignos de alcanzar las promesas de Jesucristo.\n\nOremos: Oh Dios, que concediste a tu mártir Jorge la gracia de perseverar en la fe hasta el derramamiento de su sangre, concédenos por su intercesión la fortaleza de espíritu para no ceder ante la injusticia ni ante el miedo, y el valor para defender siempre la verdad y la dignidad de todo ser humano. Por Jesucristo Nuestro Señor. Amén.",
    "en": "Litany to Saint George\n\nLord, have mercy. Christ, have mercy. Lord, have mercy.\nChrist, hear us. Christ, graciously hear us.\nGod the Father in heaven, have mercy on us.\nGod the Son, Redeemer of the world, have mercy on us.\nGod the Holy Spirit, have mercy on us.\nHoly Trinity, one God, have mercy on us.\n\nSaint George, martyr of Christ, pray for us.\nSaint George, courageous soldier, pray for us.\nSaint George, who preferred death to betrayal, pray for us.\nSaint George, conqueror of the dragon, pray for us.\nSaint George, protector of the innocent, pray for us.\nSaint George, patron of England and Catalonia, pray for us.\nSaint George, model of Christian chivalry, pray for us.\nSaint George, defender of justice, pray for us.\nSaint George, shield of the persecuted, pray for us.\nSaint George, witness to the faith unto death, pray for us.\nSaint George, patron of soldiers and scouts, pray for us.\n\nLamb of God, who takes away the sins of the world, spare us, O Lord.\nLamb of God, who takes away the sins of the world, graciously hear us, O Lord.\nLamb of God, who takes away the sins of the world, have mercy on us.\n\nV. Pray for us, Saint George,\nR. That we may be made worthy of the promises of Christ.\n\nLet us pray: O God, who granted your martyr George the grace to persevere in faith to the shedding of his blood, grant us through his intercession strength of spirit not to yield to injustice or to fear, and the courage always to defend the truth and the dignity of every human being. Through Christ our Lord. Amen."
  },
  "miracles": {
    "available": True,
    "es": "1. LA BATALLA DE DORILEA (1097) Y LA PRIMERA CRUZADA\nUno de los primeros relatos de intervención atribuida a San Jorge en la historia documentada medieval es la Batalla de Dorilea (julio de 1097), durante la Primera Cruzada. Los cronistas de la expedición, incluyendo el autor de la Gesta Francorum, relatan que los cruzados en aprietos vieron la aparición de un jinete con armadura blanca portando la cruz roja de Jorge, que les infundió ánimo en un momento crítico del combate. Este relato, transmitido por varios testigos independientes, fue uno de los factores que consolidó el culto a San Jorge en los ejércitos occidentales del medievo.\n\n2. EL CULTO EN TIERRA SANTA Y LA IGLESIA DE LIDA\nLa Iglesia de San Jorge en Lida (actual Israel), construida sobre el lugar tradicional de su martirio, es uno de los santuarios más antiguos de Tierra Santa y uno de los pocos que ha permanecido en uso continuo desde la Antigüedad tardía. Peregrinos de todas las confesiones cristianas han visitado esta iglesia durante más de quince siglos. La persistencia del culto en el lugar histórico del martirio, a pesar de conquistas, destrucciones y reconstrucciones sucesivas, es en sí mismo un testimonio notable de la fuerza de la devoción georgiana.\n\n3. PATRONAZGOS Y CONVERSIÓN POR EL EJEMPLO\nUno de los frutos espirituales más duraderos de la vida de San Jorge es la cadena de conversiones que su ejemplo provocó a lo largo de los siglos. En los relatos de su martirio, varios soldados y funcionarios romanos que presenciaron su ejecución se convirtieron al cristianismo ante la serenidad y la valentía con que enfrentó la muerte. Este efecto multiplicador del martirio — la conversión de los verdugos y de los testigos — es reconocido por la hagiografía como uno de los «milagros morales» más propios del testimonio de los mártires.",
    "en": "1. THE BATTLE OF DORYLAEUM (1097) AND THE FIRST CRUSADE\nOne of the earliest accounts of an intervention attributed to Saint George in documented medieval history is the Battle of Dorylaeum (July 1097), during the First Crusade. Chronicles of the expedition, including the author of the Gesta Francorum, report that the crusaders in distress saw the apparition of a rider in white armor bearing the red cross of George, who instilled courage in them at a critical moment of the battle. This account, transmitted by several independent witnesses, was one of the factors that consolidated the cult of Saint George in the western armies of the Middle Ages.\n\n2. THE CULT IN THE HOLY LAND AND THE CHURCH OF LYDDA\nThe Church of Saint George in Lod (present-day Israel), built on the traditional site of his martyrdom, is one of the oldest shrines in the Holy Land and one of the few that has remained in continuous use since late antiquity. Pilgrims of all Christian confessions have visited this church for more than fifteen centuries. The persistence of the cult at the historical site of the martyrdom, despite successive conquests, destructions, and reconstructions, is itself a remarkable testimony to the strength of Georgian devotion.\n\n3. PATRONAGES AND CONVERSION BY EXAMPLE\nOne of the most enduring spiritual fruits of Saint George's life is the chain of conversions that his example provoked throughout the centuries. In the accounts of his martyrdom, several Roman soldiers and officials who witnessed his execution converted to Christianity in the face of the serenity and courage with which he faced death. This multiplying effect of martyrdom — the conversion of executioners and witnesses — is recognized by hagiography as one of the 'moral miracles' most proper to the testimony of martyrs."
  }
}

out_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'sanjorge.json')
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print('sanjorge.json creado OK')
